import { definePack } from '@community/identity';

export const showcasePack = definePack({
  'pt-BR': {
    'page.kicker': 'Público',
    'page.title': 'Vitrine',
    'page.subtitle': 'Pessoas que escolheram aparecer. Contato só pela plataforma.',
    'page.off': 'Módulo de vitrine desligado.',
    'page.empty': 'Ninguém na vitrine neste momento.',
    'page.view': 'Ver perfil',
    'page.close': 'Fechar',
    'page.privacy': 'O e-mail da pessoa não aparece. A mensagem passa pela plataforma.',
    'page.pick': 'Escolha uma comunidade',
    'page.pick_subtitle': 'Cada vitrine é de um tenant. Não misturamos pessoas de comunidades diferentes nesta lista.',
    'lang.pt': 'Português',
    'lang.en': 'English',
    'lang.es': 'Espanhol',
    'lang.fr': 'Francês',
    'avail.available_for_hire': 'Disponível para contratação',
    'avail.project_partner': 'Parceiro de projeto',
    'avail.mentor': 'Mentoria',
    'avail.unavailable': 'Indisponível',
    'host.yes': 'Recebe encontros em casa',
    'link.linkedin': 'LinkedIn',
    'link.github': 'GitHub',
    'link.portfolio': 'Portfólio',
  },
  en: {
    'page.kicker': 'Public',
    'page.title': 'Showcase',
    'page.subtitle': 'People who opted in. Contact only through the platform.',
    'page.off': 'Showcase module is off.',
    'page.empty': 'Nobody on the showcase right now.',
    'page.view': 'View profile',
    'page.close': 'Close',
    'page.privacy': 'Their email stays hidden. The message goes through the platform.',
    'page.pick': 'Choose a community',
    'page.pick_subtitle': 'Each showcase belongs to one tenant. People from different communities are not mixed here.',
    'lang.pt': 'Portuguese',
    'lang.en': 'English',
    'lang.es': 'Spanish',
    'lang.fr': 'French',
    'avail.available_for_hire': 'Available for hire',
    'avail.project_partner': 'Project partner',
    'avail.mentor': 'Mentoring',
    'avail.unavailable': 'Unavailable',
    'host.yes': 'Hosts meetups at home',
    'link.linkedin': 'LinkedIn',
    'link.github': 'GitHub',
    'link.portfolio': 'Portfolio',
  },
});
