import { definePack } from '@community/identity';

export const showcasePack = definePack({
  'pt-BR': {
    'page.kicker': 'Pessoas',
    'page.title': 'Vitrine',
    'page.subtitle': 'Pessoas desta comunidade.',
    'page.off': 'A vitrine está desligada.',
    'page.empty_title': 'Ninguém nesta vitrine',
    'page.empty': 'Ninguém desta comunidade escolheu aparecer em público. Pode haver gente no diretório; aqui só entra quem deu o sim.',
    'page.empty_filtered_title': 'Nada com esse recorte',
    'page.empty_filtered': 'Ninguém combinou com a busca ou com os filtros. Tenta outro texto ou limpa o recorte.',
    'page.view': 'Ver perfil',
    'page.close': 'Fechar',
    'page.privacy': 'Mensagens passam pela plataforma. O e-mail não aparece.',
    'page.pick': 'Comunidades',
    'page.pick_subtitle': 'Abra a vitrine de uma comunidade para ver as pessoas.',
    'page.search': 'Buscar',
    'page.search_hint': 'Nome, o que faz ou a bio',
    'page.range': '{from}–{to} de {total}',
    'page.prev': 'Anterior',
    'page.next': 'Seguinte',
    'page.size': 'Por página',
    'page.filters': 'Filtros',
    'page.filters_clear': 'Limpar',
    'page.filters_hint': 'Filtros desta lista pública.',
    'page.languages': 'Idiomas',
    'page.all': 'Todos',
    'page.availability': 'Disponibilidade',
    'page.country': 'País',
    'page.city': 'Cidade',
    'page.radius': 'Raio',
    'page.radius_km': '{n} km',
    'page.view_map': 'Mapa',
    'page.view_list': 'Lista',
    'page.map_empty': 'Ninguém desta página tem lugar no mapa.',
    'lang.pt': 'Português',
    'lang.en': 'English',
    'lang.es': 'Espanhol',
    'lang.fr': 'Francês',
    'avail.available_for_hire': 'Disponível para contratação',
    'avail.project_partner': 'Parceiro de projeto',
    'avail.mentor': 'Mentoria',
    'avail.unavailable': 'Indisponível',
    'host.yes': 'Recebe encontros em casa',
    'link.linkedin': 'LinkedIn',
    'link.github': 'GitHub',
    'link.portfolio': 'Portfólio',
  },
  en: {
    'page.kicker': 'People',
    'page.title': 'Showcase',
    'page.subtitle': 'People in this community.',
    'page.off': 'The showcase is off.',
    'page.empty_title': 'Nobody on this showcase',
    'page.empty': 'Nobody in this community chose to appear in public. There may be people in the directory; this page only lists those who opted in.',
    'page.empty_filtered_title': 'Nothing in this slice',
    'page.empty_filtered': 'Nobody matched the search or the filters. Try another term, or clear the slice.',
    'page.view': 'View profile',
    'page.close': 'Close',
    'page.privacy': 'Messages go through the platform. Email stays hidden.',
    'page.pick': 'Communities',
    'page.pick_subtitle': 'Open a community showcase to meet the people.',
    'page.search': 'Search',
    'page.search_hint': 'Name, what they do, or bio',
    'page.range': '{from}–{to} of {total}',
    'page.prev': 'Previous',
    'page.next': 'Next',
    'page.size': 'Per page',
    'page.filters': 'Filters',
    'page.filters_clear': 'Clear',
    'page.filters_hint': 'Filters for this public list.',
    'page.languages': 'Languages',
    'page.all': 'All',
    'page.availability': 'Availability',
    'page.country': 'Country',
    'page.city': 'City',
    'page.radius': 'Radius',
    'page.radius_km': '{n} km',
    'page.view_map': 'Map',
    'page.view_list': 'List',
    'page.map_empty': 'Nobody on this page has a place on the map.',
    'lang.pt': 'Portuguese',
    'lang.en': 'English',
    'lang.es': 'Spanish',
    'lang.fr': 'French',
    'avail.available_for_hire': 'Available for hire',
    'avail.project_partner': 'Project partner',
    'avail.mentor': 'Mentoring',
    'avail.unavailable': 'Unavailable',
    'host.yes': 'Hosts meetups at home',
    'link.linkedin': 'LinkedIn',
    'link.github': 'GitHub',
    'link.portfolio': 'Portfolio',
  },
});
