import { definePack } from '@community/identity';

export const showcasePack = definePack({
  'pt-BR': {
    'page.kicker': 'Pessoas',
    'page.title': 'Vitrine',
    'page.subtitle': 'Pessoas desta comunidade.',
    'page.off': 'A vitrine está desligada.',
    'page.empty': 'Ninguém aparece aqui agora.',
    'page.view': 'Ver perfil',
    'page.close': 'Fechar',
    'page.privacy': 'Mensagens passam pela plataforma. O e-mail não aparece.',
    'page.pick': 'Comunidades',
    'page.pick_subtitle': 'Abra a vitrine de uma comunidade para ver as pessoas.',
    'page.search': 'Buscar',
    'page.search_hint': 'Nome, o que faz ou a bio',
    'page.count': '{n} nesta vitrine',
    'page.range': '{from}–{to} de {total}',
    'page.prev': 'Anterior',
    'page.next': 'Seguinte',
    'page.size': 'Por página',
    'page.filters': 'Filtros',
    'page.filters_clear': 'Limpar',
    'page.filters_hint': 'Disponibilidade e o que a comunidade deixou filtrar em público.',
    'page.all': 'Todos',
    'page.availability': 'Disponibilidade',
    'lang.pt': 'Português',
    'lang.en': 'English',
    'lang.es': 'Espanhol',
    'lang.fr': 'Francês',
    'avail.available_for_hire': 'Disponível para contratação',
    'avail.project_partner': 'Parceiro de projeto',
    'avail.mentor': 'Mentoria',
    'avail.unavailable': 'Indisponível',
    'host.yes': 'Recebe encontros em casa',
    'link.linkedin': 'LinkedIn',
    'link.github': 'GitHub',
    'link.portfolio': 'Portfólio',
  },
  en: {
    'page.kicker': 'People',
    'page.title': 'Showcase',
    'page.subtitle': 'People in this community.',
    'page.off': 'The showcase is off.',
    'page.empty': 'Nobody is listed here right now.',
    'page.view': 'View profile',
    'page.close': 'Close',
    'page.privacy': 'Messages go through the platform. Email stays hidden.',
    'page.pick': 'Communities',
    'page.pick_subtitle': 'Open a community showcase to meet the people.',
    'page.search': 'Search',
    'page.search_hint': 'Name, what they do, or bio',
    'page.count': '{n} on this showcase',
    'page.range': '{from}–{to} of {total}',
    'page.prev': 'Previous',
    'page.next': 'Next',
    'page.size': 'Per page',
    'page.filters': 'Filters',
    'page.filters_clear': 'Clear',
    'page.filters_hint': 'Availability and what this community made filterable in public.',
    'page.all': 'All',
    'page.availability': 'Availability',
    'lang.pt': 'Portuguese',
    'lang.en': 'English',
    'lang.es': 'Spanish',
    'lang.fr': 'French',
    'avail.available_for_hire': 'Available for hire',
    'avail.project_partner': 'Project partner',
    'avail.mentor': 'Mentoring',
    'avail.unavailable': 'Unavailable',
    'host.yes': 'Hosts meetups at home',
    'link.linkedin': 'LinkedIn',
    'link.github': 'GitHub',
    'link.portfolio': 'Portfolio',
  },
});
