'use strict';

const ROWS = [
  [
    'Opera silos e frota no cerrado',
    'Runs silos and fleet in the Cerrado',
    'Cuida de silos, balança e caminhão em entreposto de grãos. O gargalo costuma ser fila na colheita, não falta de software.',
    'Looks after silos, weighbridge and trucks at a grain depot. The bottleneck is harvest queues, not missing software.',
  ],
  [
    'Ajusta irrigação em lavoura comercial',
    'Tunes irrigation on commercial cropland',
    'Calibra pivô e turno de água em fazenda que ainda mistura caderno de campo com planilha. Perda hídrica aparece no talhão.',
    'Calibrates pivots and water shifts on a farm that still mixes field notebooks with spreadsheets. Water stress shows up in the plot.',
  ],
  [
    'Coordena cooperativa de milho e soja',
    'Coordinates a maize and soy co-op',
    'Organiza recebimento, classificação e rateio em cooperativa do Mato Grosso. Sócio quer preço na saca, não pitch de marketplace.',
    'Organizes intake, grading and cost-sharing at a Mato Grosso co-op. Members want a price per bag, not a marketplace pitch.',
  ],
  [
    'Mede umidade e impureza na balança',
    'Measures moisture and impurity at the scale',
    'Faz amostragem de carga na entrada do armazém. Discussão de desconto nasce do laudo, não de opinião no grupo da safra.',
    'Samples loads at the warehouse gate. Discount talks start from the lab sheet, not from opinions in the harvest chat.',
  ],
  [
    'Organiza logística de fertilizante a granel',
    'Organizes bulk fertilizer logistics',
    'Monta janela de descarga em pátio apertado na safra. Atraso de navio em Santos vira falta de NPK no interior.',
    'Sets unloading windows in a cramped yard at harvest. A delayed ship in Santos becomes missing NPK inland.',
  ],
  [
    'Faz crédito rural com laudo de campo',
    'Does rural credit with field reports',
    'Cruza CAR, produtividade e endividamento antes de liberar custeio. Banco pede evidência no talhão, não história de impacto.',
    'Cross-checks the rural registry, yields and debt before releasing working capital. The bank wants plot evidence, not an impact story.',
  ],
  [
    'Acompanha safra de sequeiro no oeste',
    'Follows rainfed harvest in the west',
    'Visita talhão, chuva e janela de plantio em Barreiras. Decisão de replantio sai do solo molhado, não de webinar climático.',
    'Walks plots, rainfall and planting windows in Barreiras. Replanting calls come from wet soil, not climate webinars.',
  ],
  [
    'Monta mix de bioinsumo na cooperativa',
    'Builds a bioinput mix at the co-op',
    'Testa inoculante e biofertilizante em área piloto da associação. Resultado entra no custo por saca, não em folder.',
    'Trials inoculants and biofertilizer on a co-op pilot plot. Results go into cost per bag, not a brochure.',
  ],
  [
    'Revisa outorga de água em pivô',
    'Reviews water permits for center pivots',
    'Confere vazão, poço e restrição da bacia com o irrigante. Fiscalização chega com auto, não com consultoria verde.',
    'Checks flow, wells and basin limits with the irrigator. Enforcement arrives as a fine, not as green consulting.',
  ],
  [
    'Negocia frete de soja até o porto',
    'Negotiates soy freight to the port',
    'Fecha tabela de frete rodoviário e janela de transbordo. Margem some no quilômetro rodado, não no slide de logística.',
    'Locks road freight tables and transshipment windows. Margin disappears in kilometers driven, not in a logistics slide.',
  ],
  [
    'Controla qualidade de leite em granja',
    'Controls milk quality on a dairy farm',
    'Amostra CCS e gordura em laticínio de pequena escala. Multa sanitária pesa mais que campanha de marca no Instagram.',
    'Samples somatic cells and fat at a small dairy. A sanitary fine weighs more than a brand campaign.',
  ],
  [
    'Planeja rotação de pastagem e lavoura',
    'Plans pasture and crop rotation',
    'Desenha integração em sítio que ainda usa fogo de limpeza. Só vale se o boi e a soja pagam a cerca nova.',
    'Designs crop-livestock integration on a farm that still uses clearing fires. It only holds if cattle and soy pay for the new fence.',
  ],
  [
    'Recebe hortaliça de feira e CEASA',
    'Takes in produce from markets and CEASA',
    'Classifica caixa na madrugada e devolve o que não passa. Desperdício é custo no romaneio, não métrica de ESG.',
    'Grades crates before dawn and sends back what fails. Waste is a cost on the tally sheet, not an ESG metric.',
  ],
  [
    'Expede semente tratada para o interior',
    'Ships treated seed into the interior',
    'Controla lote, validade e temperatura no barracão. Reclamação de germinação volta no caminhão, não no SAC.',
    'Tracks lot, expiry and temperature in the shed. Germination complaints come back on the truck, not through a help desk.',
  ],
  [
    'Calendariza colheita de tomate industrial',
    'Schedules industrial tomato harvest',
    'Cruza maturação, frete e janela da indústria em Goiás. Fila no pátio da fábrica estraga mais fruto que chuva.',
    'Matches ripeness, freight and factory windows in Goiás. A queue in the plant yard ruins more fruit than rain.',
  ],
  [
    'Treina brigada de queimada na fazenda',
    'Trains a farm fire brigade',
    'Organiza aceiro, rádio e escala na seca. Fogo do vizinho não espera reunião de governança climática.',
    'Sets firebreaks, radios and shifts in the dry season. A neighbor’s fire does not wait for a climate-governance meeting.',
  ],
  [
    'Fiscaliza uso de agrotóxico no talhão',
    'Audits pesticide use in the plot',
    'Confere receita agronômica, carência e EPI na pulverização. Resíduo no grão vira embargo, não debate ético.',
    'Checks prescriptions, withholding periods and PPE at spraying. Residue in grain becomes an embargo, not an ethics debate.',
  ],
  [
    'Calcula custo por saca na cooperativa',
    'Calculates cost per bag at the co-op',
    'Fecha rateio de energia, secagem e armazenagem. Associado discute centavo na assembleia, não valuation da cooperativa.',
    'Closes the split of power, drying and storage costs. Members argue over cents in the assembly, not co-op valuation.',
  ],
  [
    'Fecha contrato de milho com trading',
    'Closes a maize contract with a trader',
    'Ajusta basis, entrega e qualidade em contrato a termo. Default na safra se resolve no jurídico, não no LinkedIn.',
    'Sets basis, delivery and quality in a forward contract. A harvest default is settled legally, not on LinkedIn.',
  ],
  [
    'Mapeia nascente e APP na propriedade',
    'Maps springs and APPs on the property',
    'Marca cerca, gado e regeneração com GPS de campo. CAR desatualizado trava crédito mais que discurso ambiental.',
    'Marks fences, cattle and regeneration with field GPS. An outdated rural registry blocks credit faster than green talk.',
  ],
  [
    'Testa variedade de feijão em sequeiro',
    'Trials rainfed bean varieties',
    'Compara ciclo, praga e palhada em canteiro da associação. Adoção depende de semente barata e estável, não de marca.',
    'Compares cycle, pests and mulch on a co-op plot. Adoption depends on cheap, stable seed, not on a brand.',
  ],
  [
    'Entrega ração e correção de solo',
    'Delivers feed and soil amendment',
    'Roteiriza caminhão de calcário e núcleo em ramal de terra. Estrada ruim atrasa mais que falta de demanda no sítio.',
    'Routes lime and feed trucks down dirt side roads. A bad road delays more than weak demand at the farm.',
  ],
  [
    'Resolve conflito de água entre vizinhos',
    'Settles water conflicts between neighbors',
    'Mede poço, canal e horário de bomba na comunidade. Acordo vale se a bomba liga no turno combinado.',
    'Measures wells, canals and pump hours in the community. An agreement holds if the pump runs on the agreed shift.',
  ],
  [
    'Mantém frota de pulverizador e colheitadeira',
    'Maintains sprayer and harvester fleets',
    'Controla hora-máquina, peça e oficina no pátio. Parada na janela de plantio custa safra inteira, não só KPI.',
    'Tracks machine hours, parts and the yard workshop. A stop in the planting window costs a whole harvest, not just a KPI.',
  ],
  [
    'Compra gado magro e termina no confinamento',
    'Buys lean cattle and finishes them in feedlot',
    'Ajusta dieta, ganho e saída para frigorífico regional. Margem some na arroba e no frete, não em storytelling da carne.',
    'Adjusts diet, gain and slaughterhouse timing. Margin disappears in live weight and freight, not in a meat story.',
  ],
  [
    'Vende hortifruti para merenda escolar',
    'Sells produce to school meals',
    'Entrega nota, laudo e caixa em escola municipal do interior. Atraso de empenho quebra o produtor mais que estiagem curta.',
    'Delivers invoices, lab sheets and crates to a municipal school. A late payment order hurts the grower more than a short drought.',
  ],
  [
    'Armazena milho em silo-bolsa no pátio',
    'Stores maize in silo bags in the yard',
    'Controla lona, umidade e ataque de roedor. Perda no campo não espera vaga abrir no armazém da cooperativa.',
    'Watches liner, moisture and rodents. Field losses do not wait for a slot at the co-op warehouse.',
  ],
  [
    'Dilui calda e calibra bico no pulverizador',
    'Mixes spray mix and calibrates nozzles',
    'Ajusta dose, vento e deriva perto de nascente. Erro de calda vira multa e lavoura queimada no mesmo dia.',
    'Sets dose, wind and drift near a spring. A mixing error becomes a fine and a burned crop on the same day.',
  ],
  [
    'Colhe baru e pequi com a associação',
    'Harvests baru and pequi with the association',
    'Organiza coleta, beneficiamento e venda da castanha nativa. Preço depende de lote uniforme, não de feira de impacto.',
    'Organizes gathering, processing and sale of native nuts. Price depends on a uniform lot, not an impact fair.',
  ],
  [
    'Seca café de Cerrado em terreiro',
    'Dries Cerrado coffee on the patio',
    'Controla umidade, terreiro e blend para a cooperativa. Defeito no lote derruba classificação mais que a origem no rótulo.',
    'Controls moisture, patio drying and blend for the co-op. A defect in the lot drops the grade more than origin on the label.',
  ],
  [
    'Classifica algodão no descaroçador',
    'Grades cotton at the gin',
    'Amostra fibra, pluma e contaminante na usina. Cliente internacional recusa lote inteiro, sem aceitar desculpa de clima.',
    'Samples fiber, lint and contaminants at the gin. An international buyer rejects a whole lot; weather is not an excuse.',
  ],
  [
    'Registra trânsito de gado no entreposto',
    'Records cattle movement at the depot',
    'Confere GTA, brinco e peso na balança. Falha documental para o caminhão no pátio, mesmo com discurso de rastreio.',
    'Checks movement papers, tags and weight at the scale. Missing documents stop the truck in the yard, tracking talk aside.',
  ],
  [
    'Cruza clima e janela de plantio no oeste',
    'Crosses weather with planting windows out west',
    'Usa estação local e boletim para decidir soja precoce. Modelo de satélite não substitui lama no pé do talhão.',
    'Uses a local station and bulletins to decide on early soy. A satellite model does not replace mud on the plot.',
  ],
  [
    'Atende assistência técnica em assentamento',
    'Provides extension in a settlement',
    'Visita lote, crédito e água em projeto de reforma agrária. Atraso de ATER é calendário perdido, não falta de aplicativo.',
    'Visits plots, credit and water in a land-reform project. Late extension is a lost calendar, not a missing app.',
  ],
  [
    'Liga produtores de leite à usina',
    'Links milk producers to the plant',
    'Organiza coleta a granel e qualidade na linha rural. Tanque sujo perde o caminhão da manhã inteira.',
    'Organizes bulk collection and line quality in the countryside. A dirty tank loses the whole morning truck.',
  ],
  [
    'Desenha canal de drenagem em várzea',
    'Designs drainage canals in floodplain',
    'Marca cota, bomba e risco de cheia em horticultura. Enxurrada leva canteiro; não espera estudo de resiliência.',
    'Marks elevation, pumps and flood risk for vegetable beds. A flash flood takes the plot; it does not wait for a resilience study.',
  ],
  [
    'Implanta integração lavoura-pecuária no sítio',
    'Implements crop-livestock integration on the farm',
    'Ajusta palhada, lote e cerca em fazenda mista. Integração falha quando o pasto não fecha a conta no ano.',
    'Adjusts residue, herds and fences on a mixed farm. Integration fails when pasture does not cover the year’s costs.',
  ],
  [
    'Documenta cadeia de mandioca na cooperativa',
    'Documents the cassava chain at the co-op',
    'Registra farinha, fécula e resíduo da fecularia. Mercado local paga pontualidade de entrega, não storytelling de terroir.',
    'Records flour, starch and mill residue. The local market pays for on-time delivery, not terroir storytelling.',
  ],
  [
    'Concilia nota fiscal e romaneio de grãos',
    'Reconciles invoices and grain tallies',
    'Fecha peso, desconto e pagamento ao associado. Divergência de umidade vira assembleia feia no sábado.',
    'Closes weight, discounts and member payments. A moisture mismatch becomes an ugly Saturday assembly.',
  ],
  [
    'Rastreia lote de bioinsumo até o talhão',
    'Traces bioinput lots to the plot',
    'Controla validade, lote e aplicação em área piloto. Produto vencido no barracão não regenera solo nenhum.',
    'Tracks expiry, lots and application on a pilot area. Expired product in the shed regenerates no soil.',
  ],
  [
    'Distribui mudas nativas para APP',
    'Distributes native seedlings for APPs',
    'Entrega viveiro, cerca e replantio após seca. Mudinha morre sem água e capina, mesmo com projeto aprovado.',
    'Delivers nursery stock, fencing and replanting after drought. Seedlings die without water and weeding, approved project or not.',
  ],
  [
    'Consolida estoque de defensivo no depósito',
    'Consolidates pesticide stock in the warehouse',
    'Confere validade, receita e central de resíduo. Estoque irregular vira auto da vigilância, não workshop de boas práticas.',
    'Checks expiry, prescriptions and the residue depot. Irregular stock becomes a sanitary fine, not a best-practice workshop.',
  ],
  [
    'Opera pátio de transbordo no interior',
    'Runs an inland transshipment yard',
    'Coordena bitrem, balança e fila na safra. Gargalo é pátio molhado depois da chuva, não falta de torre de controle.',
    'Coordinates road trains, the scale and harvest queues. The bottleneck is a wet yard after rain, not a missing control tower.',
  ],
];

module.exports = ROWS;
