'use strict';

const ROWS = [
  [
    'Ensaia banda de sopro no litoral',
    'Rehearses a wind band on the coast',
    'Marca ensaio de sopros em sala da orla com umidade alta. Partitura molha; o maestro conta compassos, não likes.',
    'Schedules wind rehearsals in a seaside room with high humidity. Scores get damp; the conductor counts bars, not likes.',
  ],
  [
    'Dirige elenco em sala de ensaio úmida',
    'Directs a cast in a damp rehearsal room',
    'Monta cena de companhia estável num teatro de cidade portuária. Abertura atrasa por goteira, não por moodboard.',
    'Blocks scenes for a resident company in a port-city theatre. Opening night slips for a leak, not a mood board.',
  ],
  [
    'Ensina sapateado em piso de madeira salgada',
    'Teaches tap on salt-worn wooden floors',
    'Corrige tempo e tornozelo em estúdio perto da praia. Joelho cansa antes do espetáculo de fim de ano.',
    'Corrects timing and ankles in a studio near the beach. Knees tire before the year-end show.',
  ],
  [
    'Prepara exposição em galeria da orla',
    'Prepares a show in a waterfront gallery',
    'Instala tela e umidade controlada em espaço que fecha com ressaca. Legenda sai no texto da parede, não na bio.',
    'Hangs canvases and manages humidity in a space that shuts in a storm surge. Captions live on the wall, not in a bio.',
  ],
  [
    'Edita crônica de porto e maré',
    'Edits port and tide chronicles',
    'Corta original de quem escreve na redação pequena da costa. Fechamento é madrugada e grafia de topônimo, não thread.',
    'Cuts copy from writers in a small coastal newsroom. Close is dawn and place-name spelling, not a thread.',
  ],
  [
    'Afina piano de sala parroquial na costa',
    'Tunes a parish-hall piano on the coast',
    'Regula martelo e ferrugem depois da maresia. Recital de domingo depende da afinação, não de clipe.',
    'Regulates hammers and rust after sea air. Sunday recital depends on the tuning, not a clip.',
  ],
  [
    'Monta figurino de companhia de teatro',
    'Builds costumes for a theatre company',
    'Cose, lava e guarda roupa de temporada em camarim apertado. Tecido mofa se a janela fica aberta para o mar.',
    'Sews, washes and stores a season’s wardrobe in a tight dressing room. Cloth mildews if the window stays open to the sea.',
  ],
  [
    'Coreografa peça de rua na beira-mar',
    'Choreographs a street piece on the waterfront',
    'Marca deslocamento entre quiosque, areia e palco provisório. Ensaio para quando a maré baixa e a guarda libera a faixa.',
    'Marks paths between kiosks, sand and a temporary stage. Rehearsal waits for low tide and the guard to clear the strip.',
  ],
  [
    'Imprime gravura em ateliê da enseada',
    'Prints etchings in a cove studio',
    'Prepara tinta, prensa e papel que encrespa com umidade. Edição limitada sai numerada, não como drop.',
    'Prepares ink, press and paper that curls with humidity. A limited edition is numbered, not dropped.',
  ],
  [
    'Escreve libreto para ópera amadora',
    'Writes a libretto for amateur opera',
    'Ajusta verso e cena com coro da cidade costeira. Ensaio coral compete com horário de pescaria e ônibus.',
    'Fits verse and scenes with a coastal-town chorus. Choral rehearsal competes with fishing hours and the bus.',
  ],
  [
    'Regente de coral em igreja da orla',
    'Conducts a choir in a waterfront church',
    'Ensaia soprano e baixo com ventilador barulhento. Missa de natal precisa de ensaio extra, não de arranjo viral.',
    'Rehearses sopranos and basses with a noisy fan. Christmas mass needs extra rehearsal, not a viral arrangement.',
  ],
  [
    'Ilumina palco de teatro de arena na costa',
    'Lights an arena stage on the coast',
    'Cobre refletor contra maresia e testa dimmer velho. Escuridão no ato dois é cabo, não conceito.',
    'Covers fixtures against sea air and tests an old dimmer. Darkness in act two is a cable, not a concept.',
  ],
  [
    'Ensaia contemporâneo em piso de cimento',
    'Rehearses contemporary dance on cement',
    'Protege joelho e marca espacial em galpão de porto. Companhia viaja de van; o joelho reclama antes do cachet.',
    'Protects knees and marks space in a port warehouse. The company travels by van; knees complain before the fee arrives.',
  ],
  [
    'Cataloga acervo de fotografia de praia',
    'Catalogs a beach photography archive',
    'Digitaliza negativo mofado e ficha de autor. Pesquisa de imagem pede data e rua, não filtro vintage.',
    'Digitizes moldy negatives and author cards. Image research wants date and street, not a vintage filter.',
  ],
  [
    'Revisa original de poesia na editora local',
    'Proofs poetry manuscripts at a local press',
    'Marca verso, margens e ISBN em livro que vende na livraria da orla. Fechamento é prova impressa, não carrossel.',
    'Marks verse, margins and ISBN for a book sold at the waterfront shop. Close is a printed proof, not a carousel.',
  ],
  [
    'Ensina violão em escola municipal da costa',
    'Teaches guitar at a municipal coastal school',
    'Afina instrumento emprestado e controla falta. Recital no pátio compete com chuva e merenda atrasada.',
    'Tunes borrowed instruments and tracks absences. The courtyard recital competes with rain and a late meal.',
  ],
  [
    'Monta sonoplastia de drama em temporada',
    'Builds sound design for a season drama',
    'Corta efeito, silêncio e microfone de lapela no teatro úmido. Cue falha quando a tomada da ribalta oxida.',
    'Cuts effects, silence and lav mics in a damp theatre. Cues fail when the footlight socket oxidizes.',
  ],
  [
    'Treina elenco mirim em companhia amadora',
    'Trains a youth cast in an amateur company',
    'Marca entrada, texto e horário de responsável. Ensaio de sábado perde gente para o trabalho na feira da praia.',
    'Marks entrances, lines and guardian hours. Saturday rehearsal loses people to work at the beach market.',
  ],
  [
    'Prepara sazonal de dança folclórica na orla',
    'Prepares a seasonal folk-dance program on the shore',
    'Ensaia passo, saia e tambor para festa de padroeiro. Palco de rua depende de som da prefeitura e gerador.',
    'Rehearses steps, skirts and drums for the patron-saint feast. The street stage depends on city sound and a generator.',
  ],
  [
    'Pinta mural em muro de porto pesqueiro',
    'Paints a mural on a fishing-port wall',
    'Prepara parede, andaime e tinta que resiste a sal. Obra para quando o caminhão de gelo libera a rampa.',
    'Preps wall, scaffolding and salt-resistant paint. Work waits until the ice truck clears the ramp.',
  ],
  [
    'Escreve crítica de temporada para o jornal',
    'Writes season reviews for the paper',
    'Vê estreia, anota elenco e fecha texto na madrugada. Crítica descreve cena e plateia, não ranking de hype.',
    'Sees opening night, notes the cast and files at dawn. The review describes scene and house, not a hype ranking.',
  ],
  [
    'Repara instrumento de banda marcial',
    'Repairs marching-band instruments',
    'Solda, troca palheta e ajusta pistão depois do desfile na orla. Ensaio volta na segunda com peça ainda no óleo.',
    'Solders, changes reeds and adjusts pistons after the waterfront parade. Monday rehearsal starts with parts still in oil.',
  ],
  [
    'Ensaia texto clássico em palco italiano',
    'Rehearses a classic on a proscenium stage',
    'Marca deslocamento e voz em teatro antigo da cidade costeira. Contrarregra resolve urdimento, não o diretor no grupo.',
    'Marks blocking and voice in an old coastal theatre. The stage manager fixes the flys, not the director in the chat.',
  ],
  [
    'Dá aula de ballet em barra enferrujada',
    'Teaches ballet at a rusting barre',
    'Corrige plié e alinhamento em sala com ventilador. Recital usa figurino emprestado da temporada passada.',
    'Corrects pliés and alignment in a room with a fan. The recital uses borrowed costumes from last season.',
  ],
  [
    'Cura mostra de cerâmica na casa de cultura',
    'Curates a ceramics show at the culture house',
    'Empacota peça, seguro e ficha técnica contra maresia. Abertura espera o forno esfriar, não o convite digital.',
    'Packs pieces, insurance and labels against sea air. Opening waits for the kiln to cool, not a digital invite.',
  ],
  [
    'Oficina de roteiro em cineclube da costa',
    'Runs a screenwriting workshop at a coastal cineclub',
    'Lê cena, corte e diálogo em sessão de terça. Filme local compete com umidade do projetor e cadeira quebrada.',
    'Reads scene, cut and dialogue at a Tuesday screening. The local film competes with projector humidity and a broken chair.',
  ],
  [
    'Dirige banda de choro em clube da orla',
    'Leads a choro band at a waterfront club',
    'Marca arranjo, passagem de som e cachet dividido. Ensaio para se o salão não estiver alugado para bingo.',
    'Sets arrangements, soundcheck and a split fee. Rehearsal happens if the hall is not rented for bingo.',
  ],
  [
    'Monta cenografia com madeira de demolição',
    'Builds sets from reclaimed timber',
    'Serra, pinta e ancora cenário que viaja de caminhão pela costa. Chuva no descarrego empena o palco antes da estreia.',
    'Saws, paints and anchors a set that trucks along the coast. Rain at unload warps the stage before opening.',
  ],
  [
    'Ensaia contato-improvisação na casa de dança',
    'Rehearses contact improvisation at the dance house',
    'Cuida de peso, piso e seguro de elenco em temporada úmida. Lesão de ombro encerra ensaio mais que falta de conceito.',
    'Manages weight, floor and cast insurance in a humid season. A shoulder injury ends rehearsal faster than a missing concept.',
  ],
  [
    'Restaura quadro de acervo municipal',
    'Restores a painting from the municipal collection',
    'Limpa verniz e controla mofo em reserva técnica da orla. Laudo sai para o conselho, não para reel de restauro.',
    'Cleans varnish and controls mold in a waterfront storage room. The report goes to the council, not a restoration reel.',
  ],
  [
    'Edita coletânea de contos da costa',
    'Edits a coastal short-story collection',
    'Ordena texto, ISBN e gráfico de capa na gráfica pequena. Lançamento é mesa na livraria, não live de pré-venda.',
    'Orders text, ISBN and cover art at a small printer. Launch is a table at the bookshop, not a pre-sale live.',
  ],
  [
    'Prepara fanfarra escolar para desfile',
    'Prepares a school fanfare for the parade',
    'Ensaia marcha, farda e formação no pátio com vento. Instrumento some no ônibus; o ensaio extra é na segunda.',
    'Rehearses march, uniform and formation in a windy courtyard. An instrument goes missing on the bus; extra rehearsal is Monday.',
  ],
  [
    'Opera contraluz em casa de espetáculo',
    'Runs backlights in a performance house',
    'Troca lâmpada, gelatina e cabo oxidado pela maresia. Escuro no número de dança é fusível, não escolha estética.',
    'Changes lamps, gels and sea-oxidized cable. A blackout in the dance number is a fuse, not an aesthetic choice.',
  ],
  [
    'Ensaia companhia de teatro de bonecos',
    'Rehearses a puppet theatre company',
    'Ajusta vara, voz e camarim em temporada de escolas. Ônibus escolar atrasa o horário; o elenco espera no pátio.',
    'Adjusts rods, voice and dressing rooms on a school-season tour. The school bus is late; the cast waits in the yard.',
  ],
  [
    'Ensina dança afro em terreiro e palco',
    'Teaches Afro-Brazilian dance in terreiro and on stage',
    'Marca passo, atabaque e ensaio aberto na costa. Apresentação de padroeiro depende de som emprestado da igreja.',
    'Marks steps, drums and an open rehearsal on the coast. The patron-saint show depends on borrowed church sound.',
  ],
  [
    'Fotografa ensaio de companhia no teatro vazio',
    'Photographs a company rehearsal in an empty theatre',
    'Revela, arquiva e entrega contato para o programa de temporada. Luz de ensaio é fluorescente, não golden hour.',
    'Develops, archives and delivers contacts for the season program. Rehearsal light is fluorescent, not golden hour.',
  ],
  [
    'Escreve dramaturgia de ocupação portuária',
    'Writes a play about port labor',
    'Entrevista estivador e corta cena com a companhia. Texto descreve turno e sindicato, não metáfora de oceano genérico.',
    'Interviews dockworkers and cuts scenes with the company. The text describes shifts and the union, not a generic ocean metaphor.',
  ],
  [
    'Afina sopros de orquestra amadora da costa',
    'Tunes winds in a coastal amateur orchestra',
    'Marca ensaio seccional e conserto de chave emperrada. Concerto no teatro da orla compete com chuva no telhado.',
    'Schedules sectional rehearsal and stuck-key repairs. The waterfront concert competes with rain on the roof.',
  ],
  [
    'Monta temporada de teatro de revista',
    'Mounts a revue-theatre season',
    'Fecha número, figurino e ordem de palco em casa antiga. Plateia de fim de semana quer comicidade, não concept note.',
    'Locks numbers, costumes and running order in an old house. The weekend house wants comedy, not a concept note.',
  ],
  [
    'Dá aula de contemporâneo para terceira idade',
    'Teaches contemporary dance for older adults',
    'Adapta chão, cadeira e tempo em sala da orla. Ensaio termina no horário do ônibus, não quando a frase fecha.',
    'Adapts floor, chairs and timing in a seaside studio. Class ends with the bus, not when the phrase resolves.',
  ],
  [
    'Imprime cartaz de temporada na serigrafia',
    'Prints season posters in silkscreen',
    'Prepara tela, tinta e secagem contra umidade. Cartaz cola no poste da orla; o vento rasga o primeiro dia.',
    'Preps screen, ink and drying against humidity. Posters go on waterfront poles; wind tears them on day one.',
  ],
  [
    'Revisa tradução de peça para temporada',
    'Revises a play translation for the season',
    'Ajusta verso falado e didascália com o elenco. Ensaio de mesa descobre frase que não cabe na boca em português.',
    'Fits spoken verse and stage directions with the cast. Table rehearsal finds a line that will not sit in Portuguese.',
  ],
  [
    'Coordena camarim de festival na costa',
    'Coordinates dressing rooms at a coastal festival',
    'Organiza horário, água e troca rápida entre bandas. Atraso de uma atração empurra o palco até a maré subir.',
    'Organizes slots, water and quick changes between bands. One late act pushes the stage until the tide comes in.',
  ],
  [
    'Ensaia percussão de maracatu na quadra',
    'Rehearses maracatu percussion in the hall',
    'Marca surdo, caixa e desfile de orla. Ensaio de terça perde gente para o porto; o mestre conta de novo o toque.',
    'Marks bass drums, snares and the waterfront parade. Tuesday rehearsal loses people to the port; the mestre counts the part again.',
  ],
];

module.exports = ROWS;
