'use strict';

const ROWS = [
  [
    'Mantém pipeline da folha municipal',
    'Keeps the municipal payroll pipeline running',
    'Cuida de pipelines e qualidade de dados em organizações que ainda misturam planilha com sistema. Folha fecha mesmo com cadastro sujo.',
    'Looks after pipelines and data quality in organizations that still mix spreadsheets with systems. Payroll still closes with a dirty registry.',
  ],
  [
    'Cruza CadÚnico com frequência escolar',
    'Joins CadÚnico with school attendance',
    'Liga benefício e falta na rede municipal. Relatório para o conselho sai de SQL revisado, não de print de painel colorido.',
    'Links benefits and absences in the municipal network. The council report comes from reviewed SQL, not a colorful dashboard screenshot.',
  ],
  [
    'Monta painel de leito hospitalar',
    'Builds a hospital-bed dashboard',
    'Consolida ocupação, alta e transferência no SUS local. Plantão pede número na madrugada, não modelo de previsão elegante.',
    'Consolidates occupancy, discharge and transfers in the local SUS. The night shift wants a number at 3 a.m., not an elegant forecast.',
  ],
  [
    'Limpa base de licitação na prefeitura',
    'Cleans the city hall bidding database',
    'Padroniza CNPJ, objeto e empenho em tabela que veio de cinco sistemas. Transparência ativa quebra no campo texto livre.',
    'Standardizes tax IDs, objects and commitments in a table that came from five systems. Active transparency breaks on the free-text field.',
  ],
  [
    'Publica dado de ônibus com atraso',
    'Publishes delayed bus data',
    'Junta GPS, escala e reclamação da ouvidoria. Mapa bonito não explica por que a linha 42 some no pico.',
    'Joins GPS, shifts and ombudsman complaints. A pretty map does not explain why line 42 vanishes at peak hour.',
  ],
  [
    'Escreve SQL do orçamento da câmara',
    'Writes SQL for the city council budget',
    'Fecha empenho, liquidação e resto a pagar para a CPI interna. Vereador quer linha, não storytelling de open data.',
    'Closes commitments, liquidations and leftovers for an internal inquiry. Councilors want a line item, not an open-data story.',
  ],
  [
    'Mapeia dengue por setor censitário',
    'Maps dengue by census tract',
    'Cruza notificação, visita do ACS e criadouro. Shapefile desatualizado atrasa mutirão mais que falta de algoritmo.',
    'Joins notifications, community-agent visits and breeding sites. An outdated shapefile delays a cleanup more than a missing algorithm.',
  ],
  [
    'Treina modelo de fila no hospital',
    'Trains a queue model at the hospital',
    'Estima espera de exame com histórico de no-show. Diretoria usa o número para escala, não para paper de congresso.',
    'Estimates exam wait from no-show history. Management uses the number for staffing, not a conference paper.',
  ],
  [
    'Arquiva microdado do Censo escolar',
    'Archives school-census microdata',
    'Guarda matrícula, abandono e turno em pasta que ainda roda em Access. Pedido da secretaria chega sexta às dezoito.',
    'Stores enrollment, dropout and shifts in a folder that still lives in Access. The secretariat request arrives Friday at six.',
  ],
  [
    'Fecha apuração eleitoral no jornal',
    'Closes election tallies at the newspaper',
    'Confere zona, seção e voto com a redação. Erro de join vira manchete falsa antes da madrugada acabar.',
    'Checks precincts, sections and votes with the newsroom. A bad join becomes a false headline before dawn is over.',
  ],
  [
    'Opera lago de dados da vigilância',
    'Runs the health-surveillance data lake',
    'Ingeste SINAN, GAL e planilha de distrito. Duplicata de paciente atrasa surto mais que falta de nuvem cara.',
    'Ingests SINAN, lab systems and district spreadsheets. Duplicate patients delay an outbreak more than missing expensive cloud.',
  ],
  [
    'Revisa contrato e nota no sindicato',
    'Reviews contracts and invoices at the union',
    'Cruza folha, acordo e contribuição associativa. Tesouraria desconfia de dashboard que não bate com o extrato.',
    'Joins payroll, agreements and dues. The treasury distrusts a dashboard that does not match the bank statement.',
  ],
  [
    'Desenha mapa de alagamento com a defesa civil',
    'Draws a flood map with civil defense',
    'Junta cota, chuva e ocorrência de resgate. Camada geo sai no rádio da viatura, não só no PDF do gabinete.',
    'Joins water level, rain and rescue calls. The geo layer has to reach the radio in the truck, not only a cabinet PDF.',
  ],
  [
    'Calcula indicador de fila do Cadastro Único',
    'Calculates Cadastro Único queue indicators',
    'Mede espera, retorno e documentação incompleta no CRAS. Gestor pede corte semanal, não notebook de ciência de dados.',
    'Measures wait, returns and incomplete files at the social-assistance center. Managers want a weekly cut, not a data-science notebook.',
  ],
  [
    'Documenta API interna da educação',
    'Documents the education department’s internal API',
    'Escreve contrato de matrícula entre escolas e a secretaria. Integração quebra no código INEP duplicado, não no REST.',
    'Writes the enrollment contract between schools and the secretariat. Integration breaks on duplicate INEP codes, not on REST.',
  ],
  [
    'Testa qualidade de dado no Diário Oficial',
    'Tests data quality in the Official Gazette',
    'Valida nome, cargo e ato publicado em HTML torto. Scraping sem checagem republica erro que a cidade já corrigiu.',
    'Validates names, posts and acts in messy HTML. Unchecked scraping republishes errors the city already fixed.',
  ],
  [
    'Consolida folha e ponto no hospital',
    'Consolidates payroll and time clocks at the hospital',
    'Cruza plantão, hora extra e escala de UTI. RH ainda manda CSV por e-mail na virada do mês.',
    'Joins shifts, overtime and ICU rosters. HR still emails a CSV at month-end.',
  ],
  [
    'Entrega recorte de crime para a redação',
    'Delivers a crime cut to the newsroom',
    'Limpa Boletim de Ocorrência e geocodifica endereço ruim. Repórter precisa da rua, não de cluster de aprendizado profundo.',
    'Cleans police reports and geocodes bad addresses. The reporter needs the street, not a deep-learning cluster.',
  ],
  [
    'Implanta catálogo de tabelas na prefeitura',
    'Implements a table catalog at city hall',
    'Nomeia dono, atualização e chave de cada base. Sem isso, cada gabinete inventa a própria planilha da mesma rua.',
    'Names owner, refresh and key for each dataset. Without that, every office invents its own spreadsheet of the same street.',
  ],
  [
    'Rastreia empenho de obra no portal',
    'Traces works commitments on the portal',
    'Liga contrato, medições e atraso de canteiro. Mapa de obra parada vale mais que ranking de cidade inteligente.',
    'Links contracts, measurements and stalled sites. A map of stopped works is worth more than a smart-city ranking.',
  ],
  [
    'Amostra qualidade da água com a companhia',
    'Samples water quality with the utility',
    'Junta laudo de cloro, reclamação e setor de abastecimento. Série temporal serve para interdição, não para demo de BI.',
    'Joins chlorine lab sheets, complaints and supply zones. The time series is for a shutdown, not a BI demo.',
  ],
  [
    'Faz ETL do cadastro imobiliário',
    'Runs ETL on the property registry',
    'Une IPTU, planta e ocupação irregular. Join por logradouro falha quando a rua mudou de nome três vezes.',
    'Merges property tax, plans and irregular occupation. A join on street name fails when the street was renamed three times.',
  ],
  [
    'Opera fila de protocolo no atendimento',
    'Runs the service-desk protocol queue',
    'Mede tempo, retrabalho e sistema que cai na segunda. Ouvidoria quer causa, não nuvem de palavras da pesquisa.',
    'Measures time, rework and a system that dies on Mondays. The ombudsman wants a cause, not a word cloud from a survey.',
  ],
  [
    'Classifica denúncia ambiental no órgão',
    'Classifies environmental complaints at the agency',
    'Usa regras e um classificador simples em texto de 156. Falso positivo manda vistoria no endereço errado.',
    'Uses rules and a simple classifier on hotline text. A false positive sends an inspection to the wrong address.',
  ],
  [
    'Publica série de vacinação no jornal',
    'Publishes a vaccination series at the paper',
    'Confere dose, estoque e faixa etária com a secretaria. Gráfico sai com nota de rodapé, não com título alarmista.',
    'Checks doses, stock and age bands with the secretariat. The chart ships with a footnote, not an alarmist headline.',
  ],
  [
    'Mantém cubo de atendimento do INSS local',
    'Keeps a local INSS service cube',
    'Agrega senha, perícia e recurso numa agência lotada. Fila real não cabe no gráfico de pizza da regional.',
    'Aggregates tickets, medical exams and appeals in a crowded office. The real queue does not fit the regional pie chart.',
  ],
  [
    'Geocodifica endereço de assistência social',
    'Geocodes social-assistance addresses',
    'Corrige CEP, sem-teto e ocupação em território. Ponto no mapa errado desvia visita do CRAS a semana inteira.',
    'Fixes postcodes, homelessness and occupations in the territory. A wrong map point sends CRAS visits off-course for a week.',
  ],
  [
    'Controla versão de dado no tribunal',
    'Controls data versions at the court',
    'Guarda extrato de processo e carga diária sem sobrescrever histórico. Advogado cita a planilha de ontem como se fosse lei.',
    'Keeps case extracts and daily loads without overwriting history. Lawyers cite yesterday’s spreadsheet as if it were statute.',
  ],
  [
    'Liga nota fiscal ao estoque do hospital',
    'Links invoices to hospital inventory',
    'Cruza empenho, lote de medicamento e farmácia central. Falta de dipirona aparece no balcão antes do painel de compras.',
    'Joins commitments, drug lots and the central pharmacy. A dipyrone shortage shows up at the counter before the purchasing dashboard.',
  ],
  [
    'Audita painel de transparência salarial',
    'Audits the salary-transparency dashboard',
    'Confere cargo, gratificação e dado pessoal indevido. Publicar CPF no CSV ainda acontece, mesmo com checklist.',
    'Checks posts, bonuses and improper personal data. Publishing tax IDs in a CSV still happens, even with a checklist.',
  ],
  [
    'Extrai microdado de ônibus para pesquisa',
    'Extracts bus microdata for research',
    'Limpa GTFS torto e validadores da empresa. Pesquisador da universidade recebe dicionário, não um zip mudo.',
    'Cleans a crooked GTFS feed and fare validators. The university researcher gets a data dictionary, not a silent zip file.',
  ],
  [
    'Fecha indicador de abandono escolar',
    'Closes the school-dropout indicator',
    'Cruza frequência, transferência e código INEP. Diretor discute aluno nominal, não acurácia de um classificador.',
    'Joins attendance, transfers and school codes. The principal discusses named students, not a classifier’s accuracy.',
  ],
  [
    'Monitora qualidade de ar com a CETESB local',
    'Monitors air quality with the local CETESB desk',
    'Ingeste estação, reclamação e queima. Série furada no feriado vira manchete se ninguém avisar a redação.',
    'Ingests stations, complaints and burns. A holiday gap in the series becomes a headline if nobody warns the newsroom.',
  ],
  [
    'Padroniza logradouro no cadastro único de ruas',
    'Standardizes streets in the unique street registry',
    'Une grafia, CEP e trecho entre secretarias. Sem isso, o mesmo beco vira três territórios no mapa.',
    'Unifies spelling, postcodes and segments across departments. Without that, the same alley becomes three territories on the map.',
  ],
  [
    'Opera warehouse da folha do sindicato',
    'Runs the union payroll warehouse',
    'Carrega contribuição, processo e categoria. Tesoureiro confere soma no Excel depois de qualquer carga automatizada.',
    'Loads dues, cases and job categories. The treasurer still checks the sum in Excel after every automated load.',
  ],
  [
    'Redige dicionário de dados da saúde',
    'Writes the health-data dictionary',
    'Define CID, procedimento e unidade para o distrito. Sem glossário, cada gerente inventa a própria ocupação de leito.',
    'Defines ICD, procedures and facilities for the district. Without a glossary, every manager invents their own bed occupancy.',
  ],
  [
    'Simula corte orçamentário na educação',
    'Simulates a budget cut in education',
    'Roda cenário de merenda, transporte e contrato temporário. Número vai para a câmara, não para um paper de ML.',
    'Runs scenarios for meals, transport and temporary contracts. The number goes to the council, not an ML paper.',
  ],
  [
    'Coleta preço de cesta no mercado municipal',
    'Collects basket prices at the municipal market',
    'Monta série semanal com balança e nota. Inflação local não espera IPCA nacional sair no site.',
    'Builds a weekly series from scales and receipts. Local inflation does not wait for the national index to post.',
  ],
  [
    'Integra chamado da guarda com o 190',
    'Integrates guard calls with 190',
    'Une rádio, GPS da viatura e boletim. Duplicata de ocorrência infla estatística e esconde bairro sem viatura.',
    'Merges radio, patrol GPS and reports. Duplicate incidents inflate stats and hide neighborhoods without a car.',
  ],
  [
    'Valida censo de moradia irregular',
    'Validates a census of irregular housing',
    'Confere quadra, luz e esgoto com a equipe de campo. Modelo de satélite sozinho conta barraco onde já tem rua.',
    'Checks blocks, power and sewage with the field team. A satellite model alone counts shacks where a street already exists.',
  ],
  [
    'Publica ranking de fila de cirurgia',
    'Publishes a surgery-queue ranking',
    'Ordena especialidade, espera e regulação estadual. Família liga no outro dia; o HTML precisa abrir no celular velho.',
    'Ranks specialty, wait and statewide regulation. Families call the next day; the HTML has to open on an old phone.',
  ],
  [
    'Automatiza carga do Portal da Transparência',
    'Automates Transparency Portal loads',
    'Agenda dump, checksum e correção de encoding. Publicação atrasada vira ofício do Ministério Público, não ticket de devops.',
    'Schedules dumps, checksums and encoding fixes. A late publication becomes a prosecutor’s letter, not a devops ticket.',
  ],
  [
    'Apoia apuração de desvio em contrato',
    'Supports a contract-overrun investigation',
    'Cruza empenho, medições e nota fria para a reportagem. Prova está na linha repetida, não em rede neural de anomalia.',
    'Joins commitments, measurements and cold invoices for the story. The proof is in the repeated line, not an anomaly neural net.',
  ],
];

module.exports = ROWS;
