'use strict';

const ROWS = [
  [
    'Arquivo e memória de sindicato',
    'Union archive and memory work',
    'Organiza dossiê, ata e foto de assembleia que ainda vive em caixa. A busca só fecha quando o nome apagado da lista volta ao índice.',
    'Organizes dossiers, minutes and assembly photos that still live in boxes. A search only closes when the name erased from the list returns to the index.',
  ],
  [
    'Advocacia de contratos comerciais',
    'Commercial contracts law practice',
    'Revisa acordos de sócios, prestadores e clientes antes da assinatura. Explica o risco em português claro, sem latim de petição.',
    'Reviews shareholder, contractor and customer agreements before signature. Explains risk in plain Portuguese, without petition Latin.',
  ],
  [
    'Docência em matemática do ensino médio',
    'High-school mathematics teaching',
    'Ensina álgebra e estatística a turmas que já chegaram cansadas do dia. Monta prova que mede raciocínio, não decoreba de fórmula.',
    'Teaches algebra and statistics to classes that already arrive tired from the day. Writes tests that measure reasoning, not formula memorization.',
  ],
  [
    'Operações de varejo e estoque',
    'Retail operations and inventory',
    'Fecha loja com ruptura baixa e fila curta no caixa. Quando o sistema mente, conta prateleira com a equipe antes de pedir reposição.',
    'Closes the store with few stockouts and a short checkout line. When the system lies, counts shelves with the team before ordering restock.',
  ],
  [
    'Design gráfico para embalagens',
    'Graphic design for packaging',
    'Desenha rótulo que sobrevive à gôndola e à foto ruim do celular. Testa cor, tipo e código de barras com quem realmente empacota.',
    'Draws labels that survive the shelf and a bad phone photo. Tests color, type and barcodes with the people who actually pack the goods.',
  ],
  [
    'Eletrônica embarcada em equipamentos',
    'Embedded electronics in equipment',
    'Repara placas e firmware de máquinas que não podem parar a semana inteira. Documenta o conserto para o próximo turno achar o fio.',
    'Repairs boards and firmware on machines that cannot sit idle all week. Documents the fix so the next shift can find the wire.',
  ],
  [
    'Cozinha de restaurante e cardápio',
    'Restaurant kitchen and menu work',
    'Testa receita no pico do almoço, não só na ficha bonita. Corta desperdício sem deixar o prato parecer dieta de laboratório.',
    'Tests recipes at lunch rush, not only on a pretty spec sheet. Cuts waste without making the plate look like a lab diet.',
  ],
  [
    'Gestão de água em indústria',
    'Industrial water management',
    'Mede consumo, vazão e qualidade em plantas que ainda tratam água como custo invisível. Propõe corte que não quebra o processo.',
    'Measures use, flow and quality in plants that still treat water as an invisible cost. Proposes cuts that do not break the process.',
  ],
  [
    'Reportagem de economia e trabalho',
    'Labor and economy reporting',
    'Apura número de folha, greve e preço com fonte que fala fora do recado oficial. Entrega texto que um sindicato e um banco conseguem ler.',
    'Checks payroll figures, strikes and prices with sources who speak off the official line. Delivers copy that both a union and a bank can read.',
  ],
  [
    'Recrutamento para times operacionais',
    'Hiring for operational teams',
    'Contrata gente de chão, turno e campo sem tratar currículo como teatro. Mede o processo pelo tempo até a pessoa produzir no posto.',
    'Hires floor, shift and field people without treating CVs as theater. Judges the process by how fast someone actually produces on the job.',
  ],
  [
    'Enfermagem em unidade ambulatorial',
    'Nursing in an outpatient unit',
    'Acompanha fila, medicação e alta em ambulatório que vive no limite da agenda. Traduz o plano do médico para quem só tem dez minutos.',
    'Tracks queues, medication and discharge in an outpatient unit that lives at the edge of its schedule. Translates the doctor’s plan for someone with ten minutes.',
  ],
  [
    'Logística de última milha',
    'Last-mile logistics',
    'Roteiriza entrega quando o endereço veio incompleto e o cliente já saiu. Prefere motorista informado a painel cheio de alerta inútil.',
    'Routes deliveries when the address arrived incomplete and the customer already left. Prefers an informed driver to a dashboard full of useless alerts.',
  ],
  [
    'Contabilidade para empresas familiares',
    'Accounting for family businesses',
    'Confere livro, imposto e pró-labore em firma onde sócio e caixa ainda se misturam. Mostra o caixa real antes da reunião de família.',
    'Checks books, tax and owner draws in firms where partner and cash drawer still blur. Shows real cash before the family meeting.',
  ],
  [
    'Arquitetura de reforma residencial',
    'Residential renovation architecture',
    'Projeta reforma que cabe no orçamento e na parede existente. Discute estrutura com mestre de obras antes de vender render bonito.',
    'Designs renovations that fit the budget and the existing wall. Talks structure with the site foreman before selling a pretty render.',
  ],
  [
    'Tradução jurídica inglês português',
    'Legal translation English to Portuguese',
    'Traduz contrato e laudo sem inventar termo que o juiz não reconhece. Marca ambiguidade em vez de esconder no português elegante.',
    'Translates contracts and expert reports without inventing terms a judge would not recognize. Flags ambiguity instead of hiding it in elegant Portuguese.',
  ],
  [
    'Farmácia clínica em hospital',
    'Clinical pharmacy in a hospital',
    'Ajusta dose e interação quando o prontuário chega incompleto. Interrompe prescrição arriscada antes da gaveta de medicamento abrir.',
    'Adjusts dose and interactions when the chart arrives incomplete. Stops a risky prescription before the medicine drawer opens.',
  ],
  [
    'Gestão de acervo em biblioteca',
    'Library collection management',
    'Cataloga, descarta e empresta acervo que ainda vive em ficha e planilha. Defende espaço de leitura contra reforma que só pensa em evento.',
    'Catalogs, weeds and lends a collection that still lives on cards and spreadsheets. Defends reading space against renovations that only think about events.',
  ],
  [
    'Engenharia de som ao vivo',
    'Live sound engineering',
    'Mixa palco e PA em sala que nunca foi pensada para concerto. Chega cedo para achar o hum e o microfone que vai apitar.',
    'Mixes stage and PA in rooms that were never designed for a concert. Arrives early to find the hum and the mic that will feed back.',
  ],
  [
    'Compras industriais e fornecedores',
    'Industrial purchasing and suppliers',
    'Negocia prazo, lote e qualidade com fábrica que promete o que o pátio não entrega. Prefere visita à nota fiscal bonita.',
    'Negotiates lead time, lot size and quality with plants that promise what the yard cannot ship. Prefers a site visit to a pretty invoice.',
  ],
  [
    'Direito do trabalho em empresa',
    'In-house employment law',
    'Defende processo e acordo sem transformar RH em tribunal. Escreve política que a liderança consegue aplicar na segunda de manhã.',
    'Handles claims and settlements without turning HR into a courtroom. Writes policy that leadership can actually apply on a Monday morning.',
  ],
  [
    'Análise química de qualidade',
    'Chemical quality analysis',
    'Analisa lote, impureza e laudo em linha que não pode esperar a semana do laboratório. Recusa amostra que chegou sem cadeia de custódia.',
    'Analyzes lots, impurities and certificates on a line that cannot wait for the lab’s week. Rejects samples that arrived without a chain of custody.',
  ],
  [
    'Pesquisa com usuários de produto',
    'Product user research',
    'Observa gente usando o produto no celular ruim, não na sala de espelho. Entrega achado que o time de design consegue cortar na sprint.',
    'Watches people use the product on a bad phone, not in a mirrored lab. Delivers findings a design team can actually cut in a sprint.',
  ],
  [
    'Facilities em prédios corporativos',
    'Facilities in office buildings',
    'Mantém ar, elevador e limpeza quando o contrato de terceiros já veio folgado. Trata chamado de vazamento como prioridade, não como ticket eterno.',
    'Keeps air, lifts and cleaning going when the vendor contract already came loose. Treats a leak ticket as a priority, not an eternal ticket.',
  ],
  [
    'Preparação física de atletas amadores',
    'Strength coaching for amateur athletes',
    'Treina corredor e jogador que trabalha o dia inteiro e treina de noite. Ajusta carga para não quebrar joelho na semana do campeonato.',
    'Coaches runners and players who work all day and train at night. Adjusts load so a knee does not break in championship week.',
  ],
  [
    'Sinistros em seguros patrimoniais',
    'Property insurance claims',
    'Avalia dano, foto e laudo quando o segurado já está irritado. Separa má-fé de azar sem transformar o caso em novela de e-mail.',
    'Assesses damage, photos and reports when the insured is already angry. Separates bad faith from bad luck without turning the file into an email soap opera.',
  ],
  [
    'Edição de livros técnicos',
    'Technical book editing',
    'Edita original de engenharia e saúde até a frase caber numa página. Corta jargão que o leitor paga para não ter de decifrar sozinho.',
    'Edits engineering and health manuscripts until the sentence fits on a page. Cuts jargon readers pay not to have to decode alone.',
  ],
  [
    'Engenharia civil em obras urbanas',
    'Civil engineering on urban works',
    'Dimensiona drenagem, concreto e cronograma quando a rua não pode fechar o mês todo. Discute desvio com quem mora no quarteirão, não só com a planta.',
    'Sizes drainage, concrete and schedule when the street cannot stay closed all month. Talks detours with people who live on the block, not only with the drawing.',
  ],
  [
    'Clínica veterinária de pequenos animais',
    'Small-animal veterinary clinic',
    'Atende consulta, cirurgia e luto com tutor que chegou sem ficha. Explica exame sem vender medo no balcão.',
    'Handles consults, surgery and grief with owners who arrived without a chart. Explains tests without selling fear at the counter.',
  ],
  [
    'Conservação de acervo museológico',
    'Museum collection conservation',
    'Restaura papel, tecido e metal com orçamento que não cobre o sonho do curador. Recusa cola rápida que destrói a peça em cinco anos.',
    'Restores paper, textile and metal on a budget that cannot fund the curator’s dream. Refuses quick glue that wrecks the object in five years.',
  ],
  [
    'Relacionamento com clientes industriais',
    'Industrial customer relationship',
    'Resolve atraso, peça errada e nota fiscal antes do cliente ligar para a diretoria. Escreve o combinado depois da ligação, não só no chat.',
    'Fixes delays, wrong parts and invoices before the customer calls the board. Writes down the agreement after the call, not only in chat.',
  ],
  [
    'Folha de pagamento e encargos',
    'Payroll and statutory charges',
    'Processa salário, férias e rescisão com sindicato e eSocial no mesmo mês. Quando o holerite mente, corrige antes do dia do crédito.',
    'Runs pay, leave and termination with the union and eSocial in the same month. When the payslip lies, fixes it before payday.',
  ],
  [
    'Pré-impressão e controle de cor',
    'Prepress and color control',
    'Imprime prova até o vermelho da marca coincidir com o lote. Recusa PDF que chegou sem sangria e com fonte faltando.',
    'Prints proofs until the brand red matches the lot. Rejects PDFs that arrive without bleed and with missing fonts.',
  ],
  [
    'Tratamento de efluentes industriais',
    'Industrial effluent treatment',
    'Opera estação que precisa cumprir laudo e vizinho ao mesmo tempo. Ajusta pH e lodo sem fingir que o rio aguenta o descarte cru.',
    'Runs a plant that must satisfy both the lab report and the neighbors. Adjusts pH and sludge without pretending the river can take raw discharge.',
  ],
  [
    'Produção teatral e turnê',
    'Theatre production and touring',
    'Ensaia elenco, carga e hospedagem quando o ônibus atrasa e o teatro troca o palco. Fecha mapa de luz que um técnico local consegue executar.',
    'Rehearses cast, freight and lodging when the bus is late and the theatre swaps the stage. Locks a light plot a local tech can actually run.',
  ],
  [
    'Segurança do trabalho em fábrica',
    'Occupational safety in a factory',
    'Inspeciona máquina, EPI e quase acidente sem transformar o relatório em teatro de auditoria. Para a linha quando o risco é real, não quando o checklist pede foto.',
    'Inspects machines, PPE and near misses without turning the report into audit theater. Stops the line when the risk is real, not when the checklist wants a photo.',
  ],
  [
    'Comércio exterior e despacho',
    'Foreign trade and customs clearance',
    'Desembaraça carga quando a NCM veio errada e o prazo já queimou. Explica retenção para o comercial sem jargão de recinto alfandegado.',
    'Clears cargo when the tariff code arrived wrong and the deadline already burned. Explains a hold to sales without bonded-warehouse jargon.',
  ],
  [
    'Odontologia em clínica popular',
    'Dentistry in a community clinic',
    'Trata dor, extração e prótese em agenda que não comporta conversa longa. Explica higiene que cabe no banheiro de casa, não no consultório de revista.',
    'Treats pain, extraction and dentures on a schedule that cannot hold a long chat. Explains hygiene that fits a home bathroom, not a magazine clinic.',
  ],
  [
    'Interiores para espaços de trabalho',
    'Interiors for workplaces',
    'Escolhe mesa, luz e acústica para quem passa oito horas sentado. Recusa planta aberta que só funciona na foto do lançamento.',
    'Chooses desks, lighting and acoustics for people who sit eight hours. Refuses open plans that only work in the launch photo.',
  ],
  [
    'Produção de rádio local',
    'Local radio production',
    'Grava boletim, vinheta e entrevista com equipamento que já sobreviveu a três sedes. Corta o áudio para caber no bloco, não no ego do apresentador.',
    'Records bulletins, IDs and interviews on gear that has already survived three studios. Cuts audio to fit the slot, not the presenter’s ego.',
  ],
  [
    'Qualidade em linha de montagem',
    'Quality on an assembly line',
    'Interrompe lote quando o defeito se repete, não quando o KPI pede gráfico. Ensina o posto a achar a causa antes de culpar o turno da noite.',
    'Stops a lot when the defect repeats, not when the KPI wants a chart. Teaches the station to find the cause before blaming the night shift.',
  ],
  [
    'Coordenação pedagógica em escola',
    'School pedagogical coordination',
    'Coordena professor, família e calendário quando a prova coincidiu com a greve do ônibus. Defende tempo de aula contra reunião que só gera ata.',
    'Coordinates teachers, families and the calendar when the test landed on a bus strike. Defends class time against meetings that only produce minutes.',
  ],
  [
    'Padaria artesanal e produção',
    'Artisan bakery and production',
    'Assa pão em escala que o sábado aguenta sem virar fábrica sem gosto. Controla fermento e farinha com quem abre o forno de madrugada.',
    'Bakes bread at a scale Saturday can handle without turning tasteless factory. Controls starter and flour with whoever opens the oven before dawn.',
  ],
  [
    'Mediação de conflitos civis',
    'Civil dispute mediation',
    'Media acordo de vizinhança, família e pequeno contrato antes do processo engessar. Escreve o combinado que as duas partes reconhecem na saída.',
    'Mediates neighbor, family and small-contract disputes before litigation hardens them. Writes the agreement both sides still recognize on the way out.',
  ],
];

module.exports = ROWS;
