'use strict';

const GUEST = {
  '11:saude-territorio': [
    'Score de crédito no território',
    'Credit scoring in the territory',
    'Leva modelo de risco para a fila da UBS sem virar triagem punitiva. Discute viés quando o cadastro do território vira variável. Pede dado de atendimento, não de banco.',
    'Brings a risk model to the UBS queue without turning it into punitive triage. Argues about bias when territory registry becomes a feature. Asks for care data, not bank data.',
  ],
  '13:conservatorio-litoral': [
    'Ritos e cadastro de elenco',
    'Cast rolls and rehearsal rituals',
    'Mantém elenco e rito de ensaio sem virar grupo de WhatsApp. Mata a planilha que virou fonte da verdade da companhia. Aparece quando a casa tem mais gente do que cadeira.',
    'Keeps cast lists and rehearsal rituals from rotting into a WhatsApp group. Kills the spreadsheet that became the company’s source of truth. Shows up when the house has more people than seats.',
  ],
  '22:conservatorio-litoral': [
    'Ferramenta de aula para palco',
    'Classroom tools for the stage',
    'Faz ferramenta de aula que professor usa com internet ruim e a sala de ensaio reaproveita. Testa com quem também conduz coro jovem. O palco vira bancada de produto, não vitrine.',
    'Builds classroom tools a teacher can use on a bad connection and a rehearsal room can reuse. Tests with people who also run youth choirs. The stage becomes a product bench, not a showcase.',
  ],
  '26:saude-territorio': [
    'Cadeia curta na cozinha da UBS',
    'Short chains in the clinic kitchen',
    'Cozinha com produtor pequeno e pergunta o que a merenda da UBS realmente serve. Mapeia cadeia curta para refeição de escola e posto. O prato no território interessa mais que o cardápio bonito.',
    'Cooks with small producers and asks what the UBS kitchen actually serves. Maps short chains for school and clinic meals. The plate in the territory matters more than a pretty menu.',
  ],
  '33:mentoria-norte': [
    'Arquivo fotográfico de ramal',
    'Photographic archive of the ramal',
    'Fotografa rua, obra e caixa familiar que ia para o lixo. Mentora quem precisa de registro de ramal, não de portfólio. A câmera serve ao território, não à galeria.',
    'Photographs streets, worksites, and family boxes heading for the dump. Mentors people who need a visual record of a ramal, not a portfolio. The camera serves the territory, not the gallery.',
  ],
  '44:pratica-dados': [
    'Dado de safra e logística',
    'Harvest and logistics data',
    'Traz série de chuva e caminhão para o laboratório de dados. Monta painel que cooperativa consegue abrir no rádio ruim. Recusa dashboard que o campo não usa.',
    'Brings rain series and truck logs into the data lab. Builds a dashboard a co-op can open on a bad radio link. Refuses a dashboard the field will not use.',
  ],
  '52:cerrado-lab': [
    'Mentoria de negócio no cerrado',
    'Venture mentorship in the cerrado',
    'Traz rito de mentoria da calha para sítio e entreposto. Senta com quem tem bioinsumo e não sabe precificar. O ciclo aqui é safra, não semestre letivo.',
    'Brings mentorship ritual from the river stretch to farm and depot. Sits with people who have bioinputs and no price. The cycle here is harvest, not a school term.',
  ],
  '55:cerrado-lab': [
    'Operação de produto no campo',
    'Product operations in the field',
    'Aplica corte de produto em cooperativa que ainda mistura caderno e ERP. Corta feature que não cabe na estrada de terra. Pergunta quem colhe antes de quem investe.',
    'Applies product cuts in a co-op that still mixes notebooks and ERP. Drops features that do not fit a dirt road. Asks who harvests before who invests.',
  ],
  '65:pratica-dados': [
    'Acervo e dado de público',
    'Archive and audience data',
    'Leva controle de ensaio e bilheteria para base que dá para cruzar. Cataloga público sem virar CRM de marketing. Prefere SQL feio a slide de impacto cultural.',
    'Moves rehearsal and box-office control into a joinable base. Catalogs audiences without turning them into a marketing CRM. Prefers ugly SQL to a cultural-impact slide.',
  ],
  '66:demo': [
    'Território na rede geral',
    'Territory in the general network',
    'Traz fila, território e cadastro mentiroso para a casa ampla. Explica SUS sem virar palestra. Quem pergunta de carreira ouve sobre plantão, não sobre propósito.',
    'Brings queues, territory, and lying registries into the general house. Explains the public system without a keynote. Career questions get shift talk, not purpose talk.',
  ],
  '77:saude-territorio': [
    'Cena e cuidado no posto',
    'Stagecraft and care at the clinic',
    'Usa oficina de corpo com agente que atende morro e ramal. Ensaio de respiração vira ferramenta de acolhimento, não espetáculo. A UBS pede presença, não palco.',
    'Runs body workshops with agents who work hills and ramais. Breathing rehearsal becomes a reception tool, not a show. The UBS asks for presence, not a stage.',
  ],
  '78:mentoria-norte': [
    'Mentoria clínica no ramal',
    'Clinical mentorship on the ramal',
    'Mentora plantão e território para quem atende longe da capital. Fala de carreira sem fingir que especialização é o único caminho. O ramal manda no calendário.',
    'Mentors shifts and territory for people working far from the capital. Talks career without pretending specialization is the only path. The ramal sets the calendar.',
  ],
  '88:conservatorio-litoral': [
    'Residência e rito de palco',
    'Residency and stage ritual',
    'Leva fórum de mentoria para camarim e galpão. Organiza residência sem transformar artista em case. O norte entra como método de escuta, não como tema folclórico.',
    'Takes a mentorship forum into dressing rooms and warehouses. Runs residencies without turning artists into case studies. The North enters as a listening method, not folklore.',
  ],
  '91:conservatorio-litoral': [
    'Produção e contrato de palco',
    'Production and stage contracts',
    'Traz leitura de contrato para cia que assina o primeiro papel ruim. Lê cláusula antes do figurino. O conservatório ganha operação, não mais um voluntário entusiasmado.',
    'Brings contract reading to companies that sign the first bad paper. Reads the clause before the costume. The conservatory gains operations, not another eager volunteer.',
  ],
  '99:mentoria-norte': [
    'Mentoria com base e dúvida',
    'Mentorship with a base and doubt',
    'Mentora pesquisa e carreira com gente que ainda mistura planilha e sistema. Ensina a perguntar de onde veio o número antes do pitch. No norte, o dado serve ao ramal.',
    'Mentors research and career with people who still mix spreadsheets and systems. Teaches asking where the number came from before the pitch. In the North, data serves the ramal.',
  ],
  '104:saude-territorio': [
    'Água e alimento na APS',
    'Water and food in primary care',
    'Liga cadeia de alimento do cerrado à merenda e à farmácia do posto. Discute agrotóxico como questão de território, não de vitrine. A UBS vira ponto de escuta da safra.',
    'Links cerrado food chains to school meals and the clinic pharmacy. Treats pesticides as a territory issue, not a showcase. The UBS becomes a place to hear the harvest.',
  ],
  '110:pratica-dados': [
    'Sensor de solo em SQL',
    'Soil sensors in SQL',
    'Joga leitura de solo e granja para tabela que dá para auditar. Recusa API de startup que some no 4G ruim. O laboratório de dados vira oficina de campo.',
    'Pours soil and poultry readings into a table you can audit. Refuses a startup API that vanishes on bad 4G. The data lab becomes a field workshop.',
  ],
  '117:demo': [
    'Qualidade de dado na rede',
    'Data quality in the network',
    'Traz o hábito de perguntar a origem do número para a vitrine geral. Corta indicador que ninguém sabe calcular. A rede ganha dúvida metódica, não mais um painel.',
    'Brings the habit of asking where a number came from into the general showcase. Cuts indicators nobody can compute. The network gains methodical doubt, not another dashboard.',
  ],
  '121:cerrado-lab': [
    'Finança enxuta de cooperativa',
    'Lean co-op finance',
    'Aplica conta e contrato em associação que cresceu no WhatsApp. Fecha caixa antes do pitch de escala. O cerrado não perdoa planilha otimista.',
    'Applies accounts and contracts in an association that grew on WhatsApp. Closes the books before the scale pitch. The cerrado does not forgive an optimistic spreadsheet.',
  ],
  '130:cerrado-lab': [
    'Pesquisa aplicada em bioinsumo',
    'Applied research on bioinputs',
    'Traz mentoria de pesquisa para canteiro e barracão. Testa bioinsumo com protocolo, não com depoimento. Safra manda; o paper espera.',
    'Brings research mentorship to plots and sheds. Tests bioinputs with a protocol, not a testimonial. Harvest leads; the paper waits.',
  ],
  '132:demo': [
    'Gestão de unidade na rede',
    'Facility management in the network',
    'Explica fila, escala e território para quem na casa geral só viu produto digital. Fala de SUS sem jargão de inovação. Aqui o trabalho é operação de cuidado.',
    'Explains queues, shifts, and territory to people in the general house who only saw digital product. Talks public care without innovation jargon. The work here is care operations.',
  ],
  '143:saude-territorio': [
    'Oficina de voz no acolhimento',
    'Voice workshop at reception',
    'Leva técnica de voz e cena para a recepção do posto. Treina escuta sem transformar paciente em plateia. O território pede presença curta, não espetáculo.',
    'Takes voice and scene technique to clinic reception. Trains listening without turning patients into an audience. Territory asks for a short presence, not a show.',
  ],
  '143:pratica-dados': [
    'Catálogo de ensaio em base',
    'Rehearsal catalog in a database',
    'Transforma caderno de ensaio e figurino em tabela auditável. Cruza público e sessão sem CRM de marketing. O dado serve à companhia, não ao edital.',
    'Turns rehearsal notebooks and costumes into an auditable table. Joins audience and session without a marketing CRM. The data serves the company, not the grant form.',
  ],
  '154:conservatorio-litoral': [
    'Fórum de palco no litoral',
    'A stage forum on the coast',
    'Organiza casa de mentoria dentro de concha e galpão. Protege ensaio de reunião que só gera ata. O litoral ganha rito; o norte ganha palco.',
    'Runs a mentorship house inside bandshells and warehouses. Protects rehearsal from meetings that only produce minutes. The coast gains ritual; the North gains a stage.',
  ],
  '156:mentoria-norte': [
    'Carreira em serviço de saúde',
    'Career in health services',
    'Mentora quem sai do plantão sem mapa. Discute residência, gestão de unidade e o que o interior exige. Sem discurso de vocação; com escala real.',
    'Mentors people leaving a shift without a map. Discusses residency, facility management, and what the interior demands. No vocation speech; a real roster.',
  ],
  '165:mentoria-norte': [
    'Dado público na mentoria',
    'Public data in mentorship',
    'Leva orçamento e Cadastro Único para o ciclo de mentoria. Ensina a ler tabela antes de opinar em política. A pesquisa aqui tem fonte, não feeling.',
    'Brings budget and Cadastro Único into the mentorship cycle. Teaches reading a table before opining on policy. Research here has a source, not a feeling.',
  ],
  '169:conservatorio-litoral': [
    'Operação de temporada no palco',
    'Season operations on stage',
    'Aplica gestão de calendário em temporada que estoura figurino e cachê. Fecha data antes do cartaz. A cia ganha produtor, não mais um entusiasta.',
    'Applies calendar management to a season that blows costume and fee budgets. Locks dates before the poster. The company gains a producer, not another enthusiast.',
  ],
  '176:pratica-dados': [
    'Logística de grão em painel',
    'Grain logistics on a dashboard',
    'Modela pátio, caminhão e umidade em SQL que cooperativa abre no rádio ruim. Recusa mapa bonito sem rota. O dado vale se o silo usa.',
    'Models yards, trucks, and moisture in SQL a co-op can open on a bad radio link. Refuses a pretty map with no route. The data counts if the silo uses it.',
  ],
  '182:saude-territorio': [
    'Vigilância e cadeia curta',
    'Sanitary surveillance and short chains',
    'Cruza granja e feira com vigilância sanitária do território. Trata intoxicação e merenda como um sistema só. O posto escuta o campo, não o folder.',
    'Joins poultry yards and markets with territorial sanitary surveillance. Treats poisoning and school meals as one system. The clinic hears the field, not the brochure.',
  ],
  '187:cerrado-lab': [
    'Contrato e cofundação no sítio',
    'Contracts and cofounding on the farm',
    'Lê contrato de sócio para cooperativa que cresceu no grupo. Corta teatro de equity. O cerrado precisa de cláusula, não de pitch.',
    'Reads partner contracts for a co-op that grew in a chat group. Cuts equity theatre. The cerrado needs a clause, not a pitch.',
  ],
  '195:demo': [
    'Observatório na casa geral',
    'An observatory in the general house',
    'Traz arquivo e painel de governo para a rede ampla. Recusa indicador sem dicionário. A vitrine ganha método, não mais um recorte viral.',
    'Brings government archives and dashboards into the wider network. Refuses an indicator without a data dictionary. The showcase gains method, not another viral clip.',
  ],
  '198:demo': [
    'Cuidado e território na vitrine',
    'Care and territory in the showcase',
    'Fala de APS para quem na casa geral só conhece plano privado. Explica ramal e fila sem romantizar. A rede ouve o trabalho, não o heroísmo.',
    'Talks primary care to people in the general house who only know private plans. Explains ramal and queues without romance. The network hears the work, not heroism.',
  ],
  '208:cerrado-lab': [
    'Maloca de negócio no cerrado',
    'A business maloca in the cerrado',
    'Leva rito de casa e fórum para associação de bioinsumo. Mentora precificação sem jargão de scale-up. Safra é o sprint.',
    'Takes house and forum ritual to a bioinput association. Mentors pricing without scale-up jargon. Harvest is the sprint.',
  ],
  '209:saude-territorio': [
    'Dado de fila e território',
    'Queue and territory data',
    'Monta base de atendimento que a UBS consegue auditar. Recusa score que pune quem falta por transporte. O número serve à equipe, não ao ranking.',
    'Builds a care base a UBS can audit. Refuses a score that punishes people who miss visits for lack of transport. The number serves the team, not a ranking.',
  ],
  '220:conservatorio-litoral': [
    'Escuta de palco e ramal',
    'Stage listening and the ramal',
    'Traz método de mentoria para cia que mistura ensaio e WhatsApp. Protege o palco de reunião inútil. O litoral ensaia; o norte escuta.',
    'Brings a mentorship method to a company that mixes rehearsal and WhatsApp. Protects the stage from useless meetings. The coast rehearses; the North listens.',
  ],
  '221:pratica-dados': [
    'Bilheteria e SQL de temporada',
    'Box office and season SQL',
    'Passa venda de ingresso e ocupação para tabela. Corta métrica de impacto que ninguém calcula. A companhia lê sessão, não slogan.',
    'Moves ticket sales and occupancy into a table. Cuts impact metrics nobody computes. The company reads the session, not a slogan.',
  ],
  '231:mentoria-norte': [
    'Mentoria de pesquisa com fonte',
    'Research mentorship with sources',
    'Senta com quem quer pesquisa e ainda cola gráfico de planilha. Exige dicionário de variável. No norte, opinião sem fonte não entra no ciclo.',
    'Sits with people who want research and still paste spreadsheet charts. Demands a variable dictionary. In the North, unsourced opinion does not enter the cycle.',
  ],
  '234:mentoria-norte': [
    'Plantão e carreira no interior',
    'Shifts and career in the interior',
    'Mentora escala, cansaço e o mito da especialização. Território rural manda mais que currículo. Sem coaching; com plantão real.',
    'Mentors rosters, fatigue, and the specialization myth. Rural territory outweighs a CV. No coaching; a real shift.',
  ],
  '242:pratica-dados': [
    'Umidade e preço em série',
    'Moisture and price as a series',
    'Cruza umidade de grão com preço de pátio em série que dá para auditar. Recusa app que some offline. Cooperativa usa; o laboratório aprende.',
    'Joins grain moisture with yard prices in an auditable series. Refuses an app that vanishes offline. The co-op uses it; the lab learns.',
  ],
  '247:conservatorio-litoral': [
    'Direito e cachê de elenco',
    'Law and cast fees',
    'Traz leitura de contrato da rede geral para o elenco. Corta cláusula que come cachê. Palco precisa de leitura chata, não de fã.',
    'Brings general-network contract reading to the cast. Cuts clauses that eat the fee. The stage needs a dull reader, not a fan.',
  ],
  '253:cerrado-lab': [
    'Produto enxuto em cooperativa',
    'Lean product in a co-op',
    'Aplica corte de escopo em associação que quer app antes de balança. Pergunta o fluxo do pátio. O cerrado pune feature de vitrine.',
    'Applies scope cuts in an association that wants an app before a scale. Asks about the yard flow. The cerrado punishes showcase features.',
  ],
  '260:saude-territorio': [
    'Agrotóxico e território quilombola',
    'Pesticides and quilombola territory',
    'Leva escuta de lavoura para equipe de saúde em território quilombola. Intoxicação não é caso isolado. O posto registra o que o campo esconde.',
    'Takes crop listening to a health team in quilombola territory. Poisoning is not an isolated case. The clinic records what the field hides.',
  ],
  '264:demo': [
    'APS na conversa da rede',
    'Primary care in network talk',
    'Traduz posto, ramal e fila para a casa geral. Recusa inovação em saúde que ignora escala. O trabalho entra na vitrine sem heroísmo.',
    'Translates clinic, ramal, and queues for the general house. Refuses health innovation that ignores roster reality. The work enters the showcase without heroism.',
  ],
  '273:demo': [
    'Auditoria de número na rede',
    'Number audit in the network',
    'Leva o hábito de auditar indicador para a casa ampla. Corta métrica sem dono. A rede ganha ceticismo útil, não mais um recorte.',
    'Brings the habit of auditing indicators into the wide house. Cuts ownerless metrics. The network gains useful skepticism, not another clip.',
  ],
  '275:saude-territorio': [
    'Corpo e escuta na ESF',
    'Body and listening in the ESF',
    'Usa treino de corpo e voz com agente comunitário da ESF. Acolhimento vira técnica, não talento nato. A equipe ensaia presença, não peça.',
    'Uses body and voice training with ESF community agents. Reception becomes technique, not innate talent. The team rehearses presence, not a play.',
  ],
  '286:conservatorio-litoral': [
    'Residência sem case de impacto',
    'Residency without an impact case',
    'Organiza residência com rito de mentoria, sem transformar artista em case. Ensaio fica protegido de ata. O litoral recebe método, não turismo.',
    'Runs a residency with mentorship ritual, without turning artists into cases. Rehearsal stays protected from minutes. The coast receives a method, not tourism.',
  ],
  '286:cerrado-lab': [
    'Mentoria de safra e sócio',
    'Harvest mentorship and partners',
    'Traz ciclo de mentoria para sítio que precisa de sócio, não de guru. Precifica bioinsumo com calendário de chuva. Safra é o combinado.',
    'Brings a mentorship cycle to a farm that needs a partner, not a guru. Prices bioinputs against a rain calendar. Harvest is the agreement.',
  ],
  '297:mentoria-norte': [
    'Orçamento público no ciclo',
    'Public budget in the cycle',
    'Abre empenho e licitação no ciclo de mentoria. Ensina a ler despesa antes do discurso. Pesquisa de serviço público com fonte, não com feeling.',
    'Opens commitments and tenders in the mentorship cycle. Teaches reading spend before the speech. Public-service research with a source, not a feeling.',
  ],
  '299:pratica-dados': [
    'Luz, som e log de sessão',
    'Lights, sound, and session logs',
    'Registra luz, som e sessão em log que dá para cruzar. Recusa nuvem que cai no galpão. O dado serve à técnica, não ao making-of.',
    'Logs lights, sound, and sessions in a joinable record. Refuses a cloud that dies in the warehouse. The data serves the crew, not the making-of.',
  ],
};

module.exports = GUEST;
