'use strict';

const ROWS = [
  [
    'Orienta estágio em hospital do Guamá',
    'Mentors internships at a Guamá hospital',
    'Acompanha interno de medicina no plantão do SUS em Belém. Dúvida de carreira se resolve no corredor, não em palestra de liderança.',
    'Follows medical interns on a SUS shift in Belém. Career doubts get settled in the corridor, not in a leadership talk.',
  ],
  [
    'Pesquisa maré e pesca no Amapá',
    'Researches tides and fishing in Amapá',
    'Coleta desembarque e defeso com colônia em Macapá. Artigo só sai se o caderno de campo sobrevive à chuva no porto.',
    'Collects landings and closed-season data with a fishing colony in Macapá. The paper only ships if the field notebook survives rain at the port.',
  ],
  [
    'Prepara concurso da UFAC no Acre',
    'Prepares UFAC entrance exams in Acre',
    'Revisa edital, banca e deslocamento de candidato do interior. Barco atrasado perde prova; o sistema não espera o rio.',
    'Reviews notices, boards and inland candidates’ travel. A late boat misses the exam; the system does not wait for the river.',
  ],
  [
    'Mentora pesquisa na UFAM em Manaus',
    'Mentors research at UFAM in Manaus',
    'Lê projeto de mestrado entre energia cara e laboratório molhado. Orientação é prazo de bolsa, não ritual de networking.',
    'Reads master’s proposals between expensive power and a damp lab. Advising is a grant deadline, not a networking ritual.',
  ],
  [
    'Atende carreira no IFPA de Santarém',
    'Supports careers at IFPA in Santarém',
    'Encaminha técnico de pesca e informática para estágio no porto. Vaga some quando o navio da soja troca de escala.',
    'Places fisheries and IT technicians in port internships. The opening vanishes when the soy ship changes schedule.',
  ],
  [
    'Coordena residência no SUS de Palmas',
    'Coordinates a SUS residency in Palmas',
    'Organiza rodízio, preceptoria e deslocamento para zona rural do Tocantins. Plantão em UBS não cabe em framework de soft skill.',
    'Organizes rotations, preceptorship and travel to rural Tocantins. A UBS shift does not fit a soft-skills framework.',
  ],
  [
    'Acompanha servidor da Funai em Roraima',
    'Supports Funai staff in Roraima',
    'Ajuda relatório de campo entre Boa Vista e terra indígena. Carreira pública aqui é ofício e ramal, não marca pessoal.',
    'Helps with field reports between Boa Vista and Indigenous land. Public careers here are the job and the side road, not a personal brand.',
  ],
  [
    'Pesquisa malária em ramal do Amazonas',
    'Researches malaria on Amazonas side roads',
    'Coleta lâmina e GPS em comunidade de várzea. Publicação espera a voadeira voltar; o ciclo do mosquito não espera o Qualis.',
    'Collects slides and GPS in a floodplain community. Publication waits for the boat to return; the mosquito cycle does not wait for journal rank.',
  ],
  [
    'Orienta vestibular da Unifap em Macapá',
    'Guides Unifap admissions in Macapá',
    'Explica cota, isenção e prova para quem cruza o rio de manhã. Mentoria é edital lido em voz alta, não canvas de propósito.',
    'Explains quotas, fee waivers and the exam for people who cross the river at dawn. Mentoring is reading the notice aloud, not a purpose canvas.',
  ],
  [
    'Gestão de casa de cultura em Belém',
    'Manages a culture house in Belém',
    'Fecha escala de oficina, som e segurança na Cidade Velha. Editais atrasam cachet; o ensaio continua no salão com goteira.',
    'Closes workshop, sound and security shifts in Cidade Velha. Late grants delay fees; rehearsal still happens in a leaky hall.',
  ],
  [
    'Treina ACS em comunidade de várzea',
    'Trains community health agents in floodplain villages',
    'Revisa caderneta e deslocamento de voadeira no Pará. Formação cabe na maloca, não em módulo de e-learning instável.',
    'Reviews booklets and boat travel in Pará. Training fits in the maloca, not an unstable e-learning module.',
  ],
  [
    'Aconselha carreira docente na UFRR',
    'Advises teaching careers at UFRR',
    'Discute concurso, carga e mudança para Boa Vista. Quem vem do interior pergunta de aluguel, não de personal branding.',
    'Discusses contests, teaching loads and moving to Boa Vista. People from the interior ask about rent, not personal branding.',
  ],
  [
    'Mapeia transporte escolar no ramal',
    'Maps school transport on the ramal',
    'Cruza ônibus, barco e falta de combustível no sudoeste paraense. Pesquisa aplicada vira escala, não paper de mobilidade urbana.',
    'Joins buses, boats and fuel shortages in southwest Pará. Applied research becomes a roster, not an urban-mobility paper.',
  ],
  [
    'Mentora jornalismo na UFPA',
    'Mentors journalism at UFPA',
    'Lê pauta de território e mineração com estudante de Belém. Reportagem sai no rádio comunitário antes do site da faculdade.',
    'Reads territory and mining briefs with a Belém student. The story airs on community radio before the faculty website.',
  ],
  [
    'Opera arquivo da UFT em Palmas',
    'Runs the UFT archive in Palmas',
    'Organiza tese, diário de campo e acervo de cerrado-norte. Pesquisa histórica perde caixa quando o ar-condicionado pifa.',
    'Organizes theses, field diaries and a northern Cerrado collection. Historical research loses boxes when the air-con dies.',
  ],
  [
    'Prepara servidor novo na prefeitura de Rio Branco',
    'Onboards new staff at Rio Branco city hall',
    'Explica protocolo, diária e viagem de ramal. Mentoria pública é carimbo e prazo, não workshop de propósito.',
    'Explains protocol, travel allowances and ramal trips. Public mentoring is stamps and deadlines, not a purpose workshop.',
  ],
  [
    'Estuda regularização fundiária no Tapajós',
    'Studies land regularization on the Tapajós',
    'Cruza CAR, ocupação e conflito em comunidade ribeirinha. Orientação de mestrado cabe no mapa, não em framework de impacto.',
    'Joins rural registries, occupation and conflict in a river community. Master’s advising fits on the map, not an impact framework.',
  ],
  [
    'Encaminha técnico de enfermagem no interior',
    'Places nursing technicians inland',
    'Liga formando do IF com UBS de município pequeno no Amazonas. Contrato temporário acaba na cheia; a vaga some no Diário.',
    'Links an IF graduate with a UBS in a small Amazonas town. The temporary contract ends with the flood; the post vanishes in the gazette.',
  ],
  [
    'Pesquisa energia em comunidade isolada',
    'Researches energy in isolated communities',
    'Mede diesel, placa e apagão em ramal de Roraima. Campo cansa mais que seminário de transição energética.',
    'Measures diesel, panels and blackouts on a Roraima ramal. Fieldwork tires more than an energy-transition seminar.',
  ],
  [
    'Coordena extensão universitária em Marabá',
    'Coordinates university extension in Marabá',
    'Leva curso de direitos e saúde a sindicato rural. Extensão é ônibus e lanche, não indicador de internacionalização.',
    'Takes rights and health courses to a rural union. Extension is a bus and a snack, not an internationalization indicator.',
  ],
  [
    'Acompanha carreira de professor do Magistério',
    'Follows Magistério teaching careers',
    'Orienta progressão, lotação e escola de difícil acesso no Pará. Mentoria cabe na sala dos professores depois da última aula.',
    'Advises progression, posting and hard-to-reach schools in Pará. Mentoring fits in the staff room after the last class.',
  ],
  [
    'Organiza seletiva de residência em Manaus',
    'Organizes residency selection in Manaus',
    'Fecha prova, entrevista e vaga de clínica na capital. Candidato do interior dorme em rede de parente na semana da banca.',
    'Closes the exam, interview and clinical slots in the capital. Inland candidates sleep in a relative’s hammock during board week.',
  ],
  [
    'Documenta língua e casa de cultura no Amapá',
    'Documents language and culture houses in Amapá',
    'Grava oficina e acervo com coletivo em Macapá. Pesquisa sai em fita e ata, não em manifesto de diversidade.',
    'Records workshops and collections with a Macapá collective. Research comes out as tape and minutes, not a diversity manifesto.',
  ],
  [
    'Fiscaliza transporte fluvial escolar no Acre',
    'Audits school river transport in Acre',
    'Confere colete, horário e contrato de voadeira. Serviço público aqui é criança no banco molhado, não OKR de mobilidade.',
    'Checks life jackets, schedules and boat contracts. Public service here is a child on a wet bench, not a mobility OKR.',
  ],
  [
    'Mentora IC de climatologia na Amazônia',
    'Mentors undergrad climate research in Amazonia',
    'Revisa gráfico de chuva e estação furada no interior do AM. Bolsa acaba no meio da série; o dado não espera renovação.',
    'Reviews rainfall charts and a broken station in inland Amazonas. The grant ends mid-series; the data does not wait for renewal.',
  ],
  [
    'Atende juventude no CRAS da Compensa',
    'Serves youth at the Compensa CRAS',
    'Encaminha estágio, documento e conflito familiar em Manaus. Acolhimento é fila e xerox, não palestra motivacional.',
    'Places internships, papers and family conflict in Manaus. Reception is a queue and photocopies, not a motivational talk.',
  ],
  [
    'Pesquisa cadeia de açaí no nordeste paraense',
    'Researches the açaí chain in northeastern Pará',
    'Segue roçagem, paneiro e entreposto até Belém. Tese descreve preço na feira, não startup de bioeconomia.',
    'Follows clearing, baskets and depots into Belém. The thesis describes market prices, not a bioeconomy startup.',
  ],
  [
    'Prepara defesa de mestrado na rural da Amazônia',
    'Prepares a master’s defense at an Amazon rural campus',
    'Marca banca, passagem e energia no campus interiorano. Orientação termina quando o gerador aguenta o projetor.',
    'Books the board, tickets and power on an inland campus. Advising ends when the generator can hold the projector.',
  ],
  [
    'Liga hospital de campanha à UBS do bairro',
    'Links a field hospital to the neighborhood UBS',
    'Organiza referência e contra-referência em cheia no Pará. Serviço público é macas e barco, não transformação digital.',
    'Organizes referrals during a Pará flood. Public service is stretchers and boats, not digital transformation.',
  ],
  [
    'Aconselha saída de carreira na mineração',
    'Advises career exits from mining',
    'Conversa com técnico de Carajás sobre concurso e sindicato. Transição é FGTS e curso noturno, não jornada de propósito.',
    'Talks with a Carajás technician about contests and the union. The shift is severance and night school, not a purpose journey.',
  ],
  [
    'Mapeia vazios de especialidade no SUS estadual',
    'Maps specialty gaps in the state SUS',
    'Cruza regulação, avião da saúde e fila em Palmas. Pesquisa de serviço vira escala de médico, não framework de equidade.',
    'Joins regulation, health flights and queues in Palmas. Services research becomes a doctor roster, not an equity framework.',
  ],
  [
    'Opera rádio universitária em Santarém',
    'Runs a university radio in Santarém',
    'Fecha pauta de extensão, música e aviso de cheia. Mentoria de comunicação é locução às seis, não personal brand.',
    'Closes extension briefs, music and flood notices. Communication mentoring is a six a.m. broadcast, not a personal brand.',
  ],
  [
    'Estuda conflito de terra em Roraima',
    'Studies land conflict in Roraima',
    'Cruza processo, mapa e depoimento em Boa Vista. Orientação jurídica de campo evita slogan; o auto já existe.',
    'Joins cases, maps and testimony in Boa Vista. Field legal advising skips slogans; the police report already exists.',
  ],
  [
    'Encaminha artista para edital estadual',
    'Places artists in state grant calls',
    'Lê proposta de casa de cultura no Amapá e corrige orçamento. Mentoria cultural é nota fiscal, não speech de impacto.',
    'Reads a culture-house proposal in Amapá and fixes the budget. Cultural mentoring is invoices, not impact speeches.',
  ],
  [
    'Coleta dado de cheia na calha do Solimões',
    'Collects flood data on the Solimões corridor',
    'Mede cota, deslocamento e escola fechada entre Tabatinga e Manaus. Pesquisa espera a voadeira; o rio não espera o IRB.',
    'Measures water level, displacement and closed schools between Tabatinga and Manaus. Research waits for the boat; the river does not wait for IRB.',
  ],
  [
    'Forma preceptores de enfermagem no interior',
    'Trains nursing preceptors inland',
    'Organiza estágio em hospital pequeno do Tocantins. Carreira docente começa no plantão, não em MBA de gestão.',
    'Organizes internships in a small Tocantins hospital. A teaching career starts on the shift, not in a management MBA.',
  ],
  [
    'Revisa projeto de ramal e ponte de madeira',
    'Reviews ramal and wooden-bridge projects',
    'Confere obra, chuva e licitação em município do Acre. Serviço de engenharia pública é lama, não pitch de smart city.',
    'Checks works, rain and bidding in an Acre town. Public engineering is mud, not a smart-city pitch.',
  ],
  [
    'Mentora IC de história pública em Belém',
    'Mentors public-history research in Belém',
    'Leva estudante a arquivo e mercado do Ver-o-Peso. Pesquisa cabe na caixa-arquivo, não em storytelling de cidade criativa.',
    'Takes students to archives and Ver-o-Peso market. Research fits in an archive box, not creative-city storytelling.',
  ],
  [
    'Atende carreira de servidor da SESPA',
    'Supports SESPA staff careers',
    'Explica progressão, interiorização e plantão no Pará. Mentoria é lotação e diária, não canvas de liderança.',
    'Explains progression, inland posting and shifts in Pará. Mentoring is assignment and travel pay, not a leadership canvas.',
  ],
  [
    'Pesquisa educação escolar indígena em RR',
    'Researches Indigenous schooling in Roraima',
    'Acompanha professor, língua e merenda em escola de terra indígena. Relatório descreve ônibus e material, não inovação pedagógica genérica.',
    'Follows teachers, language and meals in a school on Indigenous land. The report describes buses and supplies, not generic pedagogical innovation.',
  ],
  [
    'Organiza mutirão de documentação em Palmas',
    'Organizes a paperwork drive in Palmas',
    'Emite RG, CPF e título com equipe itinerante no Tocantins. Cidadania aqui é fila na quadra, não jornada digital.',
    'Issues IDs, tax numbers and voter cards with a mobile team in Tocantins. Citizenship here is a queue in the hall, not a digital journey.',
  ],
  [
    'Acompanha pesquisa de pesca no Lago do Amapá',
    'Follows fisheries research on Amapá lakes',
    'Cruza desembarque, gelo e transporte até Macapá. Orientação de campo é caixa térmica, não laboratório imaginário.',
    'Joins landings, ice and transport into Macapá. Field advising is a cooler, not an imaginary lab.',
  ],
  [
    'Fecha escala de barco da saúde no Pará',
    'Closes the health-boat roster in Pará',
    'Combina médico, combustível e comunidade na calha. Mentoria de gestão pública é tanque cheio, não transformação ágil.',
    'Matches doctors, fuel and communities along the corridor. Public-management mentoring is a full tank, not agile transformation.',
  ],
];

module.exports = ROWS;
