'use strict';

const ROWS = [
  [
    'Enfermeira de UBS na periferia urbana',
    'UBS nurse in the urban periphery',
    'Faz acolhimento, curativo e escala de vacina em unidade lotada. Falta de insumo aparece no balcão antes do relatório mensal.',
    'Does reception, dressings and vaccine shifts in a crowded unit. A supply gap shows up at the counter before the monthly report.',
  ],
  [
    'Médica de família em área rural',
    'Family physician in a rural area',
    'Atende pré-natal e crônico em município pequeno. Encaminhamento espera vaga de especialidade; o ônibus não espera a regulação.',
    'Sees prenatal and chronic care in a small town. Referrals wait for a specialty slot; the bus does not wait for regulation.',
  ],
  [
    'ACS em território quilombola',
    'Community health agent in quilombola territory',
    'Visita casa, caderneta e hipertensão no território. Distância até a UBS mede-se em estrada de terra, não em raio no mapa.',
    'Visits homes, booklets and hypertension in the territory. Distance to the UBS is a dirt road, not a radius on a map.',
  ],
  [
    'Pesquisa de serviço em terra indígena',
    'Health-services research on Indigenous land',
    'Coleta indicador de pré-natal e imunização com a equipe de distrito. Relatório descreve voadeira e falta de geladeira, não framework.',
    'Collects prenatal and immunization indicators with the district team. The report describes boats and a missing fridge, not a framework.',
  ],
  [
    'Gestão de unidade no SUS periurbano',
    'Manages a peri-urban SUS facility',
    'Fecha escala, almoxarifado e manutenção em UBS da periferia. Falta de médico na terça vira fila na quarta, sem app de fila.',
    'Closes roster, stores and maintenance at a periphery UBS. A missing doctor on Tuesday becomes Wednesday’s queue, with no queue app.',
  ],
  [
    'Plantão de enfermagem em UPA da quebrada',
    'Nursing shift at a periphery UPA',
    'Triagem, medicação e contenção de crise na madrugada. Superlotação é maca no corredor, não indicador de experiência do usuário.',
    'Triage, meds and crisis containment at night. Overcrowding is a stretcher in the corridor, not a user-experience indicator.',
  ],
  [
    'Médico de saúde indígena no DSEI',
    'Indigenous-health physician at a DSEI',
    'Atende malária, pré-natal e evacuação em polo-base. Decisão clínica espera o tempo; o protocolo não encurta o rio.',
    'Treats malaria, prenatal care and evacuations at a base pole. Clinical decisions wait on the weather; the protocol does not shorten the river.',
  ],
  [
    'ACS na periferia com cadastro atrasado',
    'Community agent in the periphery with a late registry',
    'Atualiza família, visita e território no e-SUS. Microárea cresce mais rápido que a planilha da secretaria.',
    'Updates families, visits and territory in e-SUS. The micro-area grows faster than the secretariat spreadsheet.',
  ],
  [
    'Pesquisa de tuberculose em área urbana',
    'Tuberculosis research in an urban area',
    'Segue abandono de tratamento e busca ativa em favela. Dado de coorte sai da caderneta, não de wearable.',
    'Follows treatment dropout and active case-finding in a favela. Cohort data comes from the booklet, not a wearable.',
  ],
  [
    'Gerente de maternidade no interior',
    'Maternity-ward manager inland',
    'Organiza leito, sangue e transporte de risco. Cesárea de madrugada depende de plantonista e ambulância, não de protocolo laminado.',
    'Organizes beds, blood and high-risk transport. A midnight C-section depends on the on-call doctor and ambulance, not a laminated protocol.',
  ],
  [
    'Enfermeira obstétrica em casa de parto',
    'Obstetric nurse in a birth center',
    'Acompanha trabalho de parto de baixo risco e transferência. Decisão de encaminhar é clínica, não preferência de parto humanizado na internet.',
    'Follows low-risk labor and transfers. The call to refer is clinical, not a preference for “humanized birth” online.',
  ],
  [
    'Médico do NASF na zona rural',
    'NASF physician in a rural zone',
    'Faz matriciamento de saúde mental e reabilitação em UBS espalhadas. Deslocamento come o dia; o prontuário espera a volta.',
    'Does mental-health and rehab matrix support across scattered UBS units. Travel eats the day; the record waits for the return.',
  ],
  [
    'ACS de área indígena com intérprete',
    'Community agent on Indigenous land with an interpreter',
    'Traduz orientação de hipertensão e vacina na aldeia. Visita depende de permissão e calendário ritual, não de meta mensal só.',
    'Translates hypertension and vaccine guidance in the village. Visits depend on permission and ritual calendars, not monthly targets alone.',
  ],
  [
    'Pesquisa de hipertensão em quilombo',
    'Hypertension research in a quilombo',
    'Mede pressão, adesão e acesso a farmácia no território. Ensaio clínico de serviço descreve estrada, não wellness.',
    'Measures blood pressure, adherence and pharmacy access in the territory. The service trial describes the road, not wellness.',
  ],
  [
    'Gestão de farmácia em UBS da periferia',
    'Manages the pharmacy in a periphery UBS',
    'Controla lote, falta e alto custo na dispensação. Paciente volta no outro dia; o sistema de estoque cai na segunda.',
    'Tracks lots, shortages and high-cost drugs at dispensing. The patient comes back the next day; the stock system dies on Monday.',
  ],
  [
    'Técnica de enfermagem em PSF rural',
    'Nursing technician in a rural family-health team',
    'Faz curativo, coleta e visita com a equipe. Energia cai no meio da vacina; a caixa térmica não espera o gerador.',
    'Does dressings, draws and home visits with the team. Power dies mid-vaccine; the cooler does not wait for the generator.',
  ],
  [
    'Médico regulador de fila cirúrgica',
    'Physician regulating the surgical queue',
    'Ordena especialidade, risco e vaga estadual. Família liga na unidade; a regulação não explica o atraso no WhatsApp.',
    'Ranks specialty, risk and statewide slots. Families call the unit; regulation does not explain delays on WhatsApp.',
  ],
  [
    'ACS em ocupação urbana recente',
    'Community agent in a recent urban occupation',
    'Cadastra família sem CEP e endereça visita. Território muda de rua toda semana; o mapa da secretaria atrasa um mês.',
    'Registers families without postcodes and routes visits. Streets change every week; the secretariat map is a month behind.',
  ],
  [
    'Pesquisa de saúde bucal em escola rural',
    'Oral-health research in a rural school',
    'Examina cárie, flúor e falta de escova na merenda. Relatório vira mutirão, não campanha de sorriso no outdoor.',
    'Examines caries, fluoride and missing toothbrushes at mealtime. The report becomes a clinic day, not a smile billboard.',
  ],
  [
    'Diretora de UBS em território quilombola',
    'UBS director in quilombola territory',
    'Fecha escala, transporte e vínculo com parteira tradicional. Gestão é combustível e geladeira de vacina, não dashboard de NPS.',
    'Closes roster, transport and ties with traditional midwives. Management is fuel and a vaccine fridge, not an NPS dashboard.',
  ],
  [
    'Enfermeira de saúde da família na cracolândia',
    'Family-health nurse in a crackland territory',
    'Acolhe ferida, tuberculose e redução de danos na rua. Consulta acontece se a pessoa aceita; o protocolo não obriga a cadeira.',
    'Cares for wounds, TB and harm reduction on the street. The visit happens if the person accepts; the protocol cannot force the chair.',
  ],
  [
    'Médico de UPA em município da fronteira agrícola',
    'UPA physician in an agribusiness-frontier town',
    'Atende trauma, parto e intoxicação por agrotóxico. Transferência espera UTI; o caminhão da fazenda chega antes da UTI móvel.',
    'Treats trauma, birth and pesticide poisoning. Transfer waits for ICU; the farm truck arrives before the mobile ICU.',
  ],
  [
    'ACS de área rural com ramal longo',
    'Rural community agent on a long ramal',
    'Percorre casa, hipertensão e criança faltosa a cavalo ou moto. Meta de visita não cabe na chuva de novembro.',
    'Covers homes, hypertension and missing children by horse or motorcycle. Visit targets do not fit November rain.',
  ],
  [
    'Pesquisa de sífilis em pré-natal periurbano',
    'Syphilis research in peri-urban prenatal care',
    'Segue teste, tratamento e parceiro na UBS da periferia. Perda de seguimento é endereço errado, não falta de app de lembrete.',
    'Follows tests, treatment and partners at a periphery UBS. Loss to follow-up is a bad address, not a missing reminder app.',
  ],
  [
    'Gestão de SAMU em região metropolitana',
    'Manages SAMU in a metro region',
    'Fecha base, rádio e tempo-resposta na madrugada. Chamado de infarto compete com acidente na mesma viatura.',
    'Closes bases, radio and response times at night. A heart-attack call competes with a crash for the same ambulance.',
  ],
  [
    'Enfermeira de imunização em terra indígena',
    'Immunization nurse on Indigenous land',
    'Leva caixa térmica, calendário e recusa vacinal no polo. Campanha para se a voadeira e o gelo chegarem juntos.',
    'Takes a cooler, the schedule and vaccine hesitancy to the pole. The campaign waits until boat and ice arrive together.',
  ],
  [
    'Médico de família em quilombo costeiro',
    'Family physician in a coastal quilombo',
    'Atende diabetes, ferida e pré-natal com maré. Consulta extra espera a canoa; o prontuário eletrônico cai com a internet.',
    'Treats diabetes, wounds and prenatal care with the tide. Extra visits wait for the canoe; the electronic record dies with the internet.',
  ],
  [
    'ACS urbana de saúde mental na microárea',
    'Urban mental-health community agent in a micro-area',
    'Visita crise, medicação e CAPS de referência. Acolhimento é porta e vizinho, não feed de bem-estar.',
    'Visits crises, medication and the referral CAPS. Care is the door and the neighbor, not a wellness feed.',
  ],
  [
    'Pesquisa de mortalidade materna no interior',
    'Maternal-mortality research inland',
    'Revisa óbito, pré-natal e atraso de transferência. Comitê descreve ambulância e sangue, não storytelling de empoderamento.',
    'Reviews deaths, prenatal care and delayed transfer. The committee describes ambulances and blood, not empowerment storytelling.',
  ],
  [
    'Gerente de CAPS na periferia',
    'CAPS manager in the periphery',
    'Organiza oficina, medicação e crise na unidade. Falta de psiquiatra na escala vira contenção no corredor.',
    'Organizes workshops, medication and crises in the unit. A missing psychiatrist on the roster becomes restraint in the corridor.',
  ],
  [
    'Técnica de enfermagem em hospital indígena',
    'Nursing technician in an Indigenous hospital',
    'Faz medicação, curativo e tradução no internamento. Alta depende de acompanhante e transporte, não de score de satisfação.',
    'Gives meds, dressings and translation on the ward. Discharge depends on a companion and transport, not a satisfaction score.',
  ],
  [
    'Médico do trabalho em frigorífico e UBS',
    'Occupational physician between slaughterhouse and UBS',
    'Vê LER, corte e retorno ao trabalho na periferia industrial. Atestado discute função, não coaching de postura.',
    'Sees RSI, cuts and return-to-work on the industrial edge. The sick note discusses the job, not posture coaching.',
  ],
  [
    'ACS quilombola de saúde da mulher',
    'Quilombola community agent in women’s health',
    'Acompanha preventivo, pré-natal e violência no território. Encaminhamento é ônibus e vergonha na fila, não quiz de autocuidado.',
    'Follows screening, prenatal care and violence in the territory. Referral is a bus and shame in the queue, not a self-care quiz.',
  ],
  [
    'Pesquisa de dengue em periferia urbana',
    'Dengue research in the urban periphery',
    'Cruza criadouro, visita e internação na UPA. Mutirão descreve caixa-d’água, não laboratório de inovação climática.',
    'Joins breeding sites, visits and UPA admissions. The cleanup describes water tanks, not a climate-innovation lab.',
  ],
  [
    'Gestão de imunização municipal',
    'Manages municipal immunization',
    'Fecha sala de vacina, perda e campanha extra. Dose vence na geladeira da UBS quando a energia cai no fim de semana.',
    'Closes vaccine rooms, wastage and extra campaigns. Doses expire in the UBS fridge when power dies on the weekend.',
  ],
  [
    'Enfermeira de curativo em pé diabético rural',
    'Wound-care nurse for rural diabetic foot',
    'Faz desbridamento, orientação e retorno na UBS do interior. Amputação espera vaga; o paciente volta de moto com o curativo molhado.',
    'Does debridement, teaching and follow-up at an inland UBS. Amputation waits for a slot; the patient rides back with a wet dressing.',
  ],
  [
    'Médico de saúde da família em aldeia',
    'Family physician in a village',
    'Atende infecção, desnutrição e evacuação com a equipe multidisciplinar. Clínica respeita liderança local; o protocolo não substitui o conselho.',
    'Treats infection, malnutrition and evacuation with the multidisciplinary team. Clinic respects local leadership; the protocol does not replace the council.',
  ],
  [
    'ACS periurbana de hipertensão e diabetes',
    'Peri-urban community agent for hypertension and diabetes',
    'Confere pressão, glicemia e falta de medicamento na visita. Meta de cadastro não mede quem trabalha fora no horário da visita.',
    'Checks blood pressure, glucose and missing meds on visits. Registry targets do not count people who work during visit hours.',
  ],
  [
    'Pesquisa de atenção básica em território quilombola',
    'Primary-care research in quilombola territory',
    'Avalia acesso, vínculo e tempo de espera na UBS. Achado descreve estrada e vínculo, não jornada do paciente em app.',
    'Assesses access, continuity and wait at the UBS. Findings describe the road and the bond, not a patient journey in an app.',
  ],
  [
    'Diretor de hospital pequeno no interior',
    'Director of a small inland hospital',
    'Fecha UTI, oxigênio e plantão de cirurgia. Falta de anestesista cancela lista; o WhatsApp da secretaria não traz o profissional.',
    'Closes ICU, oxygen and surgical call. A missing anesthetist cancels the list; the secretariat WhatsApp does not produce the professional.',
  ],
  [
    'Enfermeira de sala de vacina na periferia',
    'Vaccine-room nurse in the periphery',
    'Aplica dose, registra e acalma fila com criança. Sistema cai; a caderneta de papel ainda segura o calendário.',
    'Gives doses, records them and calms a queue of children. The system dies; the paper booklet still holds the schedule.',
  ],
  [
    'Médico plantonista de obstetrícia no SUS',
    'On-call obstetrician in the SUS',
    'Cobre parto, curetagem e transferência de risco. Plantão é sangue e vaga de UTI, não rotina de wellness perinatal.',
    'Covers birth, curettage and high-risk transfer. The shift is blood and an ICU bed, not perinatal wellness routine.',
  ],
  [
    'ACS de busca ativa de faltoso vacinal',
    'Community agent on vaccine catch-up',
    'Procura criança faltosa em casa e escola da periferia. Recusa se discute na porta, não em campanha de influenciador.',
    'Finds missing children at homes and schools in the periphery. Refusal is discussed at the door, not in an influencer campaign.',
  ],
  [
    'Gestão de vigilância em território indígena',
    'Manages surveillance in Indigenous territory',
    'Fecha notificação, surto e bloqueio vacinal no distrito. Relatório semanal descreve aldeia e gelo, não observatório de inovação.',
    'Closes notifications, outbreaks and vaccine blockades in the district. The weekly report describes villages and ice, not an innovation observatory.',
  ],
];

module.exports = ROWS;
