import { nestCatalog, type CatalogGroup } from './catalog';

const loc = (pt: string, en: string) => [
  { locale: 'pt-BR' as const, value: pt },
  { locale: 'en' as const, value: en },
];

export function coreCatalog(): CatalogGroup[] {
  return nestCatalog([
    {
      group_slug: 'identity',
      group_label: loc('Identidade', 'Identity'),
      group_description: loc('Nome e foto.', 'Name and photo.'),
      columns: 1,
      name: 'full_name',
      type: 'text',
      label: loc('Nome completo', 'Full name'),
      storage: 'person',
      column_key: 'full_name',
      span: 1,
      required: true,
    },
    {
      group_slug: 'identity',
      group_label: loc('Identidade', 'Identity'),
      group_description: loc('Nome e foto.', 'Name and photo.'),
      columns: 1,
      name: 'avatar_url',
      type: 'url',
      label: loc('URL do avatar', 'Avatar URL'),
      storage: 'person',
      column_key: 'avatar_url',
      span: 1,
    },
    {
      group_slug: 'person',
      group_label: loc('Pessoa', 'Person'),
      group_description: loc('Demografia e links.', 'Demographics and links.'),
      columns: 3,
      name: 'gender',
      type: 'select',
      label: loc('Gênero', 'Gender'),
      storage: 'person',
      column_key: 'gender',
      span: 3,
      options: [
        { value: 'woman', label: loc('Mulher', 'Woman') },
        { value: 'man', label: loc('Homem', 'Man') },
        { value: 'non_binary', label: loc('Não binário', 'Non-binary') },
        { value: 'prefer_not', label: loc('Prefiro não dizer', 'Prefer not to say') },
      ],
    },
    {
      group_slug: 'person',
      group_label: loc('Pessoa', 'Person'),
      group_description: loc('Demografia e links.', 'Demographics and links.'),
      columns: 3,
      name: 'birth_city',
      type: 'city',
      label: loc('Cidade de nascimento', 'City of birth'),
      storage: 'person',
      column_key: 'birth_city',
      span: 1,
    },
    {
      group_slug: 'person',
      group_label: loc('Pessoa', 'Person'),
      group_description: loc('Demografia e links.', 'Demographics and links.'),
      columns: 3,
      name: 'current_city',
      type: 'city',
      label: loc('Cidade onde mora', 'City of residence'),
      storage: 'person',
      column_key: 'current_city',
      span: 1,
    },
    {
      group_slug: 'person',
      group_label: loc('Pessoa', 'Person'),
      group_description: loc('Demografia e links.', 'Demographics and links.'),
      columns: 3,
      name: 'languages',
      type: 'checkbox',
      label: loc('Idiomas que fala', 'Languages spoken'),
      storage: 'person',
      column_key: 'languages',
      span: 3,
      options: [
        { value: 'pt', label: loc('pt', 'pt') },
        { value: 'en', label: loc('en', 'en') },
        { value: 'es', label: loc('es', 'es') },
        { value: 'fr', label: loc('fr', 'fr') },
      ],
    },
    {
      group_slug: 'person',
      group_label: loc('Pessoa', 'Person'),
      group_description: loc('Demografia e links.', 'Demographics and links.'),
      columns: 3,
      name: 'linkedin',
      type: 'url',
      label: loc('LinkedIn', 'LinkedIn'),
      storage: 'person',
      column_key: 'contacts.linkedin',
      span: 1,
    },
    {
      group_slug: 'person',
      group_label: loc('Pessoa', 'Person'),
      group_description: loc('Demografia e links.', 'Demographics and links.'),
      columns: 3,
      name: 'github',
      type: 'url',
      label: loc('GitHub', 'GitHub'),
      storage: 'person',
      column_key: 'contacts.github',
      span: 1,
    },
    {
      group_slug: 'person',
      group_label: loc('Pessoa', 'Person'),
      group_description: loc('Demografia e links.', 'Demographics and links.'),
      columns: 3,
      name: 'portfolio',
      type: 'url',
      label: loc('Portfólio', 'Portfolio'),
      storage: 'person',
      column_key: 'contacts.portfolio',
      span: 1,
    },
  ]);
}
