import { definePack } from '@community/identity';

export const directoryPack = definePack({
  'pt-BR': {
    'page.kicker': 'Membros',
    'page.title': 'Pessoas',
    'page.subtitle': 'Quem está ativo nesta comunidade.',
    'page.search': 'Nome ou título',
    'page.empty': 'Ninguém ativo nesta comunidade.',
    'page.off': 'O diretório está desligado.',
    'page.privacy': 'A mensagem passa pela plataforma. O e-mail da pessoa não aparece.',
    'page.view': 'Ver perfil',
    'page.close': 'Fechar',
    'page.filters': 'Filtros',
    'page.filters_clear': 'Limpar',
    'page.filters_hint': 'Campos que a comunidade deixou filtrar nesta lista.',
    'page.languages': 'Idiomas',
    'page.all': 'Todos',
    'page.cohort': 'Turma',
    'card.section': 'Nesta comunidade',
    'card.headline': 'Título',
    'card.bio': 'Apresentação',
    'card.availability': 'Disponibilidade',
    'card.showcase': 'Mostrar na vitrine pública',
    'card.hire': 'Disponível para contratação',
    'card.partner': 'Parceiro de projeto',
    'card.mentor': 'Mentoria',
    'card.unavailable': 'Indisponível',
    'card.proficiency': 'Proficiência',
  },
  en: {
    'page.kicker': 'Members',
    'page.title': 'People',
    'page.subtitle': 'Who is active in this community.',
    'page.search': 'Name or title',
    'page.empty': 'No one active in this community.',
    'page.off': 'The directory is off.',
    'page.privacy': 'The message goes through the platform. Their email stays hidden.',
    'page.view': 'View profile',
    'page.close': 'Close',
    'page.filters': 'Filters',
    'page.filters_clear': 'Clear',
    'page.filters_hint': 'Fields this community made filterable on this list.',
    'page.languages': 'Languages',
    'page.all': 'All',
    'page.cohort': 'Cohort',
    'card.section': 'This community',
    'card.headline': 'Title',
    'card.bio': 'About',
    'card.availability': 'Availability',
    'card.showcase': 'Show on the public showcase',
    'card.hire': 'Available for hire',
    'card.partner': 'Project partner',
    'card.mentor': 'Mentoring',
    'card.unavailable': 'Unavailable',
    'card.proficiency': 'Proficiency',
  },
});
