import { definePack } from '@community/identity';

export const directoryPack = definePack({
  'pt-BR': {
    'page.kicker': 'Membros',
    'page.title': 'Encontre pessoas da rede',
    'page.subtitle': 'Diretório intermediado. Contato sem e-mail público.',
    'page.search': 'Buscar por nome ou headline',
    'page.empty': 'Nenhum membro ativo nesta comunidade.',
    'page.off': 'Módulo de diretório desligado.',
    'page.privacy': 'Contato intermediado. O e-mail direto não aparece aqui.',
    'page.view': 'Ver perfil',
    'card.section': 'Nesta comunidade',
    'card.headline': 'Headline',
    'card.bio': 'Bio',
    'card.availability': 'Disponibilidade',
    'card.showcase': 'Mostrar na vitrine pública',
    'card.hire': 'Disponível para contratação',
    'card.partner': 'Parceiro de projeto',
    'card.mentor': 'Mentoria',
    'card.unavailable': 'Indisponível',
    'card.proficiency': 'Proficiência',
  },
  en: {
    'page.kicker': 'Members',
    'page.title': 'Find people in the network',
    'page.subtitle': 'Mediated directory. No public email.',
    'page.search': 'Search by name or headline',
    'page.empty': 'No active members in this community.',
    'page.off': 'Directory module is off.',
    'page.privacy': 'Mediated contact. Direct email is hidden.',
    'page.view': 'View profile',
    'card.section': 'This community',
    'card.headline': 'Headline',
    'card.bio': 'Bio',
    'card.availability': 'Availability',
    'card.showcase': 'Show on the public showcase',
    'card.hire': 'Available for hire',
    'card.partner': 'Project partner',
    'card.mentor': 'Mentoring',
    'card.unavailable': 'Unavailable',
    'card.proficiency': 'Proficiency',
  },
});
